#pragma once
#include "NFS_XtendedInput_XInputConfig.h"

#define XBONE_A_HASH 0x29790E5B
#define XBONE_B_HASH 0x29790E5C
#define XBONE_DPAD_HASH 0xEABB3693
#define XBONE_DPAD_DOWN_HASH 0x2BF107AA
#define XBONE_DPAD_LEFT_HASH 0x2BF53DFD
#define XBONE_DPAD_RIGHT_HASH 0xAB0BC530
#define XBONE_DPAD_UP_HASH 0x52C9B117
#define XBONE_DPAD_X_HASH 0x866333EA
#define XBONE_DPAD_Y_HASH 0x866333EB
#define XBONE_LANALOG_HASH 0x98877D78
#define XBONE_LANALOG_DOWN_HASH 0xB88665AF
#define XBONE_LANALOG_LEFT_HASH 0xB88A9C02
#define XBONE_LANALOG_RIGHT_HASH 0xCA4CE3D5
#define XBONE_LANALOG_UP_HASH 0xE3F5C9DC
#define XBONE_LANALOG_X_HASH 0xD85CC80F
#define XBONE_LANALOG_Y_HASH 0xD85CC810
#define XBONE_LB_HASH 0x589ADB68
#define XBONE_LS_HASH 0x589ADB79
#define XBONE_LT_HASH 0x589ADB7A
#define XBONE_MENU_HASH 0xEABFF8EF
#define XBONE_RANALOG_HASH 0x6664E9FE
#define XBONE_RANALOG_DOWN_HASH 0xDE3A95F5
#define XBONE_RANALOG_LEFT_HASH 0xDE3ECC48
#define XBONE_RANALOG_RIGHT_HASH 0xA6871CDB
#define XBONE_RANALOG_UP_HASH 0xFC3530A2
#define XBONE_RANALOG_X_HASH 0x93476E15
#define XBONE_RANALOG_Y_HASH 0x93476E16
#define XBONE_RB_HASH 0x589ADC2E
#define XBONE_RS_HASH 0x589ADC3F
#define XBONE_RT_HASH 0x589ADC40
#define XBONE_VIEW_HASH 0xEAC4F835
#define XBONE_X_HASH 0x29790E72
#define XBONE_Y_HASH 0x29790E73

#define PS4_CIRCLE_HASH 0xB225CEC7
#define PS4_CROSS_HASH 0x8189EAFF
#define PS4_DPAD_HASH 0xD561C72E
#define PS4_DPAD_DOWN_HASH 0xFEC13125
#define PS4_DPAD_LEFT_HASH 0xFEC56778
#define PS4_DPAD_RIGHT_HASH 0xD7E11E0B
#define PS4_DPAD_UP_HASH 0x52FB3FD2
#define PS4_DPAD_X_HASH 0xB4F05745
#define PS4_DPAD_Y_HASH 0xB4F05746
#define PS4_L1_HASH 0x739E8932
#define PS4_L2_HASH 0x739E8933
#define PS4_L3_HASH 0x739E8934
#define PS4_LANALOG_HASH 0x98B90C33
#define PS4_LANALOG_DOWN_HASH 0x7015614A
#define PS4_LANALOG_LEFT_HASH 0x7019979D
#define PS4_LANALOG_RIGHT_HASH 0x73BB52D0
#define PS4_LANALOG_UP_HASH 0x10CB22B7
#define PS4_LANALOG_X_HASH 0xAB2CF18A
#define PS4_LANALOG_Y_HASH 0xAB2CF18B
#define PS4_R1_HASH 0x739E89F8
#define PS4_R2_HASH 0x739E89F9
#define PS4_R3_HASH 0x739E89FA
#define PS4_RANALOG_HASH 0x669678B9
#define PS4_RANALOG_DOWN_HASH 0x95C99190
#define PS4_RANALOG_LEFT_HASH 0x95CDC7E3
#define PS4_RANALOG_RIGHT_HASH 0x4FF58BD6
#define PS4_RANALOG_UP_HASH 0x290A897D
#define PS4_RANALOG_X_HASH 0x66179790
#define PS4_RANALOG_Y_HASH 0x66179791
#define PS4_SHARE_HASH 0x82A5BB88
#define PS4_SQUARE_HASH 0xD80ABA46
#define PS4_START_HASH 0x82AC5023
#define PS4_TRIANGLE_HASH 0x22DE6EEB


unsigned int GetAppropriateButtonTex(WORD buttonmask)
{
	switch (ControllerIconMode)
	{
	case CONTROLLERICON_PS4:
		switch (buttonmask)
		{
		case XINPUT_GAMEPAD_DPAD_UP:
			return PS4_DPAD_UP_HASH;
		case XINPUT_GAMEPAD_DPAD_DOWN:
			return PS4_DPAD_DOWN_HASH;
		case XINPUT_GAMEPAD_DPAD_LEFT:
			return PS4_DPAD_LEFT_HASH;
		case XINPUT_GAMEPAD_DPAD_RIGHT:
			return PS4_DPAD_RIGHT_HASH;
		case XINPUT_GAMEPAD_START:
			return PS4_START_HASH;
		case XINPUT_GAMEPAD_BACK:
			return PS4_SHARE_HASH;
		case XINPUT_GAMEPAD_LEFT_THUMB:
			return PS4_L3_HASH;
		case XINPUT_GAMEPAD_RIGHT_THUMB:
			return PS4_R3_HASH;
		case XINPUT_GAMEPAD_LEFT_SHOULDER:
			return PS4_L1_HASH;
		case XINPUT_GAMEPAD_RIGHT_SHOULDER:
			return PS4_R1_HASH;
		case XINPUT_GAMEPAD_A:
			return PS4_CROSS_HASH;
		case XINPUT_GAMEPAD_B:
			return PS4_CIRCLE_HASH;
		case XINPUT_GAMEPAD_X:
			return PS4_SQUARE_HASH;
		case XINPUT_GAMEPAD_Y:
			return PS4_TRIANGLE_HASH;
		case XINPUT_GAMEPAD_LT_CONFIGDEF:
			return PS4_L2_HASH;
		case XINPUT_GAMEPAD_RT_CONFIGDEF:
			return PS4_R2_HASH;
		case XINPUT_GAMEPAD_LS_X_CONFIGDEF:
			return PS4_LANALOG_X_HASH;
		case XINPUT_GAMEPAD_LS_Y_CONFIGDEF:
			return PS4_LANALOG_Y_HASH;
		case XINPUT_GAMEPAD_RS_X_CONFIGDEF:
			return PS4_RANALOG_X_HASH;
		case XINPUT_GAMEPAD_RS_Y_CONFIGDEF:
			return PS4_RANALOG_Y_HASH;
		case XINPUT_GAMEPAD_LS_UP_CONFIGDEF:
			return PS4_LANALOG_UP_HASH;
		case XINPUT_GAMEPAD_LS_DOWN_CONFIGDEF:
			return PS4_LANALOG_DOWN_HASH;
		case XINPUT_GAMEPAD_LS_LEFT_CONFIGDEF:
			return PS4_LANALOG_LEFT_HASH;
		case XINPUT_GAMEPAD_LS_RIGHT_CONFIGDEF:
			return PS4_LANALOG_RIGHT_HASH;
		case XINPUT_GAMEPAD_RS_UP_CONFIGDEF:
			return PS4_RANALOG_UP_HASH;
		case XINPUT_GAMEPAD_RS_DOWN_CONFIGDEF:
			return PS4_RANALOG_DOWN_HASH;
		case XINPUT_GAMEPAD_RS_LEFT_CONFIGDEF:
			return PS4_RANALOG_LEFT_HASH;
		case XINPUT_GAMEPAD_RS_RIGHT_CONFIGDEF:
			return PS4_RANALOG_RIGHT_HASH;
		case XINPUT_GAMEPAD_DPAD_CONFIGDEF:
			return PS4_DPAD_HASH;
		case XINPUT_GAMEPAD_DPAD_UPDOWN_CONFIGDEF:
			return PS4_DPAD_Y_HASH;
		case XINPUT_GAMEPAD_DPAD_LEFTRIGHT_CONFIGDEF:
			return PS4_DPAD_X_HASH;
		case XINPUT_GAMEPAD_LS_CONFIGDEF:
			return PS4_LANALOG_HASH;
		case XINPUT_GAMEPAD_RS_CONFIGDEF:
			return PS4_RANALOG_HASH;

		default:
			break;
		}
	case CONTROLLERICON_XBOXONE:
	default:
		switch (buttonmask)
		{
		case XINPUT_GAMEPAD_DPAD_UP:
			return XBONE_DPAD_UP_HASH;
		case XINPUT_GAMEPAD_DPAD_DOWN:
			return XBONE_DPAD_DOWN_HASH;
		case XINPUT_GAMEPAD_DPAD_LEFT:
			return XBONE_DPAD_LEFT_HASH;
		case XINPUT_GAMEPAD_DPAD_RIGHT:
			return XBONE_DPAD_RIGHT_HASH;
		case XINPUT_GAMEPAD_START:
			return XBONE_MENU_HASH;
		case XINPUT_GAMEPAD_BACK:
			return XBONE_VIEW_HASH;
		case XINPUT_GAMEPAD_LEFT_THUMB:
			return XBONE_LS_HASH;
		case XINPUT_GAMEPAD_RIGHT_THUMB:
			return XBONE_RS_HASH;
		case XINPUT_GAMEPAD_LEFT_SHOULDER:
			return XBONE_LB_HASH;
		case XINPUT_GAMEPAD_RIGHT_SHOULDER:
			return XBONE_RB_HASH;
		case XINPUT_GAMEPAD_A:
			return XBONE_A_HASH;
		case XINPUT_GAMEPAD_B:
			return XBONE_B_HASH;
		case XINPUT_GAMEPAD_X:
			return XBONE_X_HASH;
		case XINPUT_GAMEPAD_Y:
			return XBONE_Y_HASH;
		case XINPUT_GAMEPAD_LT_CONFIGDEF:
			return XBONE_LT_HASH;
		case XINPUT_GAMEPAD_RT_CONFIGDEF:
			return XBONE_RT_HASH;
		case XINPUT_GAMEPAD_LS_X_CONFIGDEF:
			return XBONE_LANALOG_X_HASH;
		case XINPUT_GAMEPAD_LS_Y_CONFIGDEF:
			return XBONE_LANALOG_Y_HASH;
		case XINPUT_GAMEPAD_RS_X_CONFIGDEF:
			return XBONE_RANALOG_X_HASH;
		case XINPUT_GAMEPAD_RS_Y_CONFIGDEF:
			return XBONE_RANALOG_Y_HASH;
		case XINPUT_GAMEPAD_LS_UP_CONFIGDEF:
			return XBONE_LANALOG_UP_HASH;
		case XINPUT_GAMEPAD_LS_DOWN_CONFIGDEF:
			return XBONE_LANALOG_DOWN_HASH;
		case XINPUT_GAMEPAD_LS_LEFT_CONFIGDEF:
			return XBONE_LANALOG_LEFT_HASH;
		case XINPUT_GAMEPAD_LS_RIGHT_CONFIGDEF:
			return XBONE_LANALOG_RIGHT_HASH;
		case XINPUT_GAMEPAD_RS_UP_CONFIGDEF:
			return XBONE_RANALOG_UP_HASH;
		case XINPUT_GAMEPAD_RS_DOWN_CONFIGDEF:
			return XBONE_RANALOG_DOWN_HASH;
		case XINPUT_GAMEPAD_RS_LEFT_CONFIGDEF:
			return XBONE_RANALOG_LEFT_HASH;
		case XINPUT_GAMEPAD_RS_RIGHT_CONFIGDEF:
			return XBONE_RANALOG_RIGHT_HASH;
		case XINPUT_GAMEPAD_DPAD_CONFIGDEF:
			return XBONE_DPAD_HASH;
		case XINPUT_GAMEPAD_DPAD_UPDOWN_CONFIGDEF:
			return XBONE_DPAD_Y_HASH;
		case XINPUT_GAMEPAD_DPAD_LEFTRIGHT_CONFIGDEF:
			return XBONE_DPAD_X_HASH;
		case XINPUT_GAMEPAD_LS_CONFIGDEF:
			return XBONE_LANALOG_HASH;
		case XINPUT_GAMEPAD_RS_CONFIGDEF:
			return XBONE_RANALOG_HASH;

		default:
			break;
		}
		break;
	}
	return 0;
}
