#pragma once
#include <windows.h>
 int bStringHash(char* a1);

#define VK_LBUTTON_HASH							HASH("VK_LBUTTON_HASH")							
#define VK_RBUTTON_HASH							HASH("VK_RBUTTON_HASH")							
#define VK_CANCEL_HASH							HASH("VK_CANCEL_HASH")							
#define VK_MBUTTON_HASH							HASH("VK_MBUTTON_HASH")							
#define VK_XBUTTON1_HASH						HASH("VK_XBUTTON1_HASH")						
#define VK_XBUTTON2_HASH						HASH("VK_XBUTTON2_HASH")						
#define VK_BACK_HASH							HASH("VK_BACK_HASH")							
#define VK_TAB_HASH								HASH("VK_TAB_HASH")								
#define VK_CLEAR_HASH							HASH("VK_CLEAR_HASH")							
#define VK_RETURN_HASH							HASH("VK_RETURN_HASH")							
#define VK_SHIFT_HASH							HASH("VK_SHIFT_HASH")							
#define VK_CONTROL_HASH							HASH("VK_CONTROL_HASH")							
#define VK_MENU_HASH							HASH("VK_MENU_HASH")							
#define VK_PAUSE_HASH							HASH("VK_PAUSE_HASH")							
#define VK_CAPITAL_HASH							HASH("VK_CAPITAL_HASH")							
#define VK_KANA_HASH							HASH("VK_KANA_HASH")							
#define VK_HANGEUL_HASH							HASH("VK_HANGEUL_HASH")							
#define VK_HANGUL_HASH							HASH("VK_HANGUL_HASH")							
#define VK_IME_ON_HASH							HASH("VK_IME_ON_HASH")							
#define VK_JUNJA_HASH							HASH("VK_JUNJA_HASH")							
#define VK_FINAL_HASH							HASH("VK_FINAL_HASH")							
#define VK_HANJA_HASH							HASH("VK_HANJA_HASH")							
#define VK_KANJI_HASH							HASH("VK_KANJI_HASH")							
#define VK_IME_OFF_HASH							HASH("VK_IME_OFF_HASH")							
#define VK_ESCAPE_HASH							HASH("VK_ESCAPE_HASH")							
#define VK_CONVERT_HASH							HASH("VK_CONVERT_HASH")							
#define VK_NONCONVERT_HASH						HASH("VK_NONCONVERT_HASH")						
#define VK_ACCEPT_HASH							HASH("VK_ACCEPT_HASH")							
#define VK_MODECHANGE_HASH						HASH("VK_MODECHANGE_HASH")						
#define VK_SPACE_HASH							HASH("VK_SPACE_HASH")							
#define VK_PRIOR_HASH							HASH("VK_PRIOR_HASH")							
#define VK_NEXT_HASH							HASH("VK_NEXT_HASH")							
#define VK_END_HASH								HASH("VK_END_HASH")								
#define VK_HOME_HASH							HASH("VK_HOME_HASH")							
#define VK_LEFT_HASH							HASH("VK_LEFT_HASH")							
#define VK_UP_HASH								HASH("VK_UP_HASH")								
#define VK_RIGHT_HASH							HASH("VK_RIGHT_HASH")							
#define VK_DOWN_HASH							HASH("VK_DOWN_HASH")							
#define VK_SELECT_HASH							HASH("VK_SELECT_HASH")							
#define VK_PRINT_HASH							HASH("VK_PRINT_HASH")							
#define VK_EXECUTE_HASH							HASH("VK_EXECUTE_HASH")							
#define VK_SNAPSHOT_HASH						HASH("VK_SNAPSHOT_HASH")						
#define VK_INSERT_HASH							HASH("VK_INSERT_HASH")							
#define VK_DELETE_HASH							HASH("VK_DELETE_HASH")							
#define VK_HELP_HASH							HASH("VK_HELP_HASH")							
#define VK_LWIN_HASH							HASH("VK_LWIN_HASH")							
#define VK_RWIN_HASH							HASH("VK_RWIN_HASH")							
#define VK_APPS_HASH							HASH("VK_APPS_HASH")							
#define VK_SLEEP_HASH							HASH("VK_SLEEP_HASH")							
#define VK_NUMPAD0_HASH							HASH("VK_NUMPAD0_HASH")							
#define VK_NUMPAD1_HASH							HASH("VK_NUMPAD1_HASH")							
#define VK_NUMPAD2_HASH							HASH("VK_NUMPAD2_HASH")							
#define VK_NUMPAD3_HASH							HASH("VK_NUMPAD3_HASH")							
#define VK_NUMPAD4_HASH							HASH("VK_NUMPAD4_HASH")							
#define VK_NUMPAD5_HASH							HASH("VK_NUMPAD5_HASH")							
#define VK_NUMPAD6_HASH							HASH("VK_NUMPAD6_HASH")							
#define VK_NUMPAD7_HASH							HASH("VK_NUMPAD7_HASH")							
#define VK_NUMPAD8_HASH							HASH("VK_NUMPAD8_HASH")							
#define VK_NUMPAD9_HASH							HASH("VK_NUMPAD9_HASH")							
#define VK_MULTIPLY_HASH						HASH("VK_MULTIPLY_HASH")						
#define VK_ADD_HASH								HASH("VK_ADD_HASH")								
#define VK_SEPARATOR_HASH						HASH("VK_SEPARATOR_HASH")						
#define VK_SUBTRACT_HASH						HASH("VK_SUBTRACT_HASH")						
#define VK_DECIMAL_HASH							HASH("VK_DECIMAL_HASH")							
#define VK_DIVIDE_HASH							HASH("VK_DIVIDE_HASH")							
#define VK_F1_HASH								HASH("VK_F1_HASH")								
#define VK_F2_HASH								HASH("VK_F2_HASH")								
#define VK_F3_HASH								HASH("VK_F3_HASH")								
#define VK_F4_HASH								HASH("VK_F4_HASH")								
#define VK_F5_HASH								HASH("VK_F5_HASH")								
#define VK_F6_HASH								HASH("VK_F6_HASH")								
#define VK_F7_HASH								HASH("VK_F7_HASH")								
#define VK_F8_HASH								HASH("VK_F8_HASH")								
#define VK_F9_HASH								HASH("VK_F9_HASH")								
#define VK_F10_HASH								HASH("VK_F10_HASH")								
#define VK_F11_HASH								HASH("VK_F11_HASH")								
#define VK_F12_HASH								HASH("VK_F12_HASH")								
#define VK_F13_HASH								HASH("VK_F13_HASH")								
#define VK_F14_HASH								HASH("VK_F14_HASH")								
#define VK_F15_HASH								HASH("VK_F15_HASH")								
#define VK_F16_HASH								HASH("VK_F16_HASH")								
#define VK_F17_HASH								HASH("VK_F17_HASH")								
#define VK_F18_HASH								HASH("VK_F18_HASH")								
#define VK_F19_HASH								HASH("VK_F19_HASH")								
#define VK_F20_HASH								HASH("VK_F20_HASH")								
#define VK_F21_HASH								HASH("VK_F21_HASH")								
#define VK_F22_HASH								HASH("VK_F22_HASH")								
#define VK_F23_HASH								HASH("VK_F23_HASH")								
#define VK_F24_HASH								HASH("VK_F24_HASH")								
#define VK_NAVIGATION_VIEW_HASH					HASH("VK_NAVIGATION_VIEW_HASH")					
#define VK_NAVIGATION_MENU_HASH					HASH("VK_NAVIGATION_MENU_HASH")					
#define VK_NAVIGATION_UP_HASH					HASH("VK_NAVIGATION_UP_HASH")					
#define VK_NAVIGATION_DOWN_HASH					HASH("VK_NAVIGATION_DOWN_HASH")					
#define VK_NAVIGATION_LEFT_HASH					HASH("VK_NAVIGATION_LEFT_HASH")					
#define VK_NAVIGATION_RIGHT_HASH				HASH("VK_NAVIGATION_RIGHT_HASH")				
#define VK_NAVIGATION_ACCEPT_HASH				HASH("VK_NAVIGATION_ACCEPT_HASH")				
#define VK_NAVIGATION_CANCEL_HASH				HASH("VK_NAVIGATION_CANCEL_HASH")				
#define VK_NUMLOCK_HASH							HASH("VK_NUMLOCK_HASH")							
#define VK_SCROLL_HASH							HASH("VK_SCROLL_HASH")							
#define VK_OEM_NEC_EQUAL_HASH					HASH("VK_OEM_NEC_EQUAL_HASH")					
#define VK_OEM_FJ_JISHO_HASH					HASH("VK_OEM_FJ_JISHO_HASH")					
#define VK_OEM_FJ_MASSHOU_HASH					HASH("VK_OEM_FJ_MASSHOU_HASH")					
#define VK_OEM_FJ_TOUROKU_HASH					HASH("VK_OEM_FJ_TOUROKU_HASH")					
#define VK_OEM_FJ_LOYA_HASH						HASH("VK_OEM_FJ_LOYA_HASH")						
#define VK_OEM_FJ_ROYA_HASH						HASH("VK_OEM_FJ_ROYA_HASH")						
#define VK_LSHIFT_HASH							HASH("VK_LSHIFT_HASH")							
#define VK_RSHIFT_HASH							HASH("VK_RSHIFT_HASH")							
#define VK_LCONTROL_HASH						HASH("VK_LCONTROL_HASH")						
#define VK_RCONTROL_HASH						HASH("VK_RCONTROL_HASH")						
#define VK_LMENU_HASH							HASH("VK_LMENU_HASH")							
#define VK_RMENU_HASH							HASH("VK_RMENU_HASH")							
#define VK_BROWSER_BACK_HASH					HASH("VK_BROWSER_BACK_HASH")					
#define VK_BROWSER_FORWARD_HASH					HASH("VK_BROWSER_FORWARD_HASH")					
#define VK_BROWSER_REFRESH_HASH					HASH("VK_BROWSER_REFRESH_HASH")					
#define VK_BROWSER_STOP_HASH					HASH("VK_BROWSER_STOP_HASH")					
#define VK_BROWSER_SEARCH_HASH					HASH("VK_BROWSER_SEARCH_HASH")					
#define VK_BROWSER_FAVORITES_HASH				HASH("VK_BROWSER_FAVORITES_HASH")				
#define VK_BROWSER_HOME_HASH					HASH("VK_BROWSER_HOME_HASH")					
#define VK_VOLUME_MUTE_HASH						HASH("VK_VOLUME_MUTE_HASH")						
#define VK_VOLUME_DOWN_HASH						HASH("VK_VOLUME_DOWN_HASH")						
#define VK_VOLUME_UP_HASH						HASH("VK_VOLUME_UP_HASH")						
#define VK_MEDIA_NEXT_TRACK_HASH				HASH("VK_MEDIA_NEXT_TRACK_HASH")				
#define VK_MEDIA_PREV_TRACK_HASH				HASH("VK_MEDIA_PREV_TRACK_HASH")				
#define VK_MEDIA_STOP_HASH						HASH("VK_MEDIA_STOP_HASH")						
#define VK_MEDIA_PLAY_PAUSE_HASH				HASH("VK_MEDIA_PLAY_PAUSE_HASH")				
#define VK_LAUNCH_MAIL_HASH						HASH("VK_LAUNCH_MAIL_HASH")						
#define VK_LAUNCH_MEDIA_SELECT_HASH				HASH("VK_LAUNCH_MEDIA_SELECT_HASH")				
#define VK_LAUNCH_APP1_HASH						HASH("VK_LAUNCH_APP1_HASH")						
#define VK_LAUNCH_APP2_HASH						HASH("VK_LAUNCH_APP2_HASH")						
#define VK_OEM_1_HASH							HASH("VK_OEM_1_HASH")							
#define VK_OEM_PLUS_HASH						HASH("VK_OEM_PLUS_HASH")						
#define VK_OEM_COMMA_HASH						HASH("VK_OEM_COMMA_HASH")						
#define VK_OEM_MINUS_HASH						HASH("VK_OEM_MINUS_HASH")						
#define VK_OEM_PERIOD_HASH						HASH("VK_OEM_PERIOD_HASH")						
#define VK_OEM_2_HASH							HASH("VK_OEM_2_HASH")							
#define VK_OEM_3_HASH							HASH("VK_OEM_3_HASH")							
#define VK_GAMEPAD_A_HASH						HASH("VK_GAMEPAD_A_HASH")						
#define VK_GAMEPAD_B_HASH						HASH("VK_GAMEPAD_B_HASH")						
#define VK_GAMEPAD_X_HASH						HASH("VK_GAMEPAD_X_HASH")						
#define VK_GAMEPAD_Y_HASH						HASH("VK_GAMEPAD_Y_HASH")						
#define VK_GAMEPAD_RIGHT_SHOULDER_HASH			HASH("VK_GAMEPAD_RIGHT_SHOULDER_HASH")			
#define VK_GAMEPAD_LEFT_SHOULDER_HASH			HASH("VK_GAMEPAD_LEFT_SHOULDER_HASH")			
#define VK_GAMEPAD_LEFT_TRIGGER_HASH			HASH("VK_GAMEPAD_LEFT_TRIGGER_HASH")			
#define VK_GAMEPAD_RIGHT_TRIGGER_HASH			HASH("VK_GAMEPAD_RIGHT_TRIGGER_HASH")			
#define VK_GAMEPAD_DPAD_UP_HASH					HASH("VK_GAMEPAD_DPAD_UP_HASH")					
#define VK_GAMEPAD_DPAD_DOWN_HASH				HASH("VK_GAMEPAD_DPAD_DOWN_HASH")				
#define VK_GAMEPAD_DPAD_LEFT_HASH				HASH("VK_GAMEPAD_DPAD_LEFT_HASH")				
#define VK_GAMEPAD_DPAD_RIGHT_HASH				HASH("VK_GAMEPAD_DPAD_RIGHT_HASH")				
#define VK_GAMEPAD_MENU_HASH					HASH("VK_GAMEPAD_MENU_HASH")					
#define VK_GAMEPAD_VIEW_HASH					HASH("VK_GAMEPAD_VIEW_HASH")					
#define VK_GAMEPAD_LEFT_THUMBSTICK_BUTTON_HASH	HASH("VK_GAMEPAD_LEFT_THUMBSTICK_BUTTON_HASH")	
#define VK_GAMEPAD_RIGHT_THUMBSTICK_BUTTON_HASH	HASH("VK_GAMEPAD_RIGHT_THUMBSTICK_BUTTON_HASH")	
#define VK_GAMEPAD_LEFT_THUMBSTICK_UP_HASH		HASH("VK_GAMEPAD_LEFT_THUMBSTICK_UP_HASH")		
#define VK_GAMEPAD_LEFT_THUMBSTICK_DOWN_HASH	HASH("VK_GAMEPAD_LEFT_THUMBSTICK_DOWN_HASH")	
#define VK_GAMEPAD_LEFT_THUMBSTICK_RIGHT_HASH	HASH("VK_GAMEPAD_LEFT_THUMBSTICK_RIGHT_HASH")	
#define VK_GAMEPAD_LEFT_THUMBSTICK_LEFT_HASH	HASH("VK_GAMEPAD_LEFT_THUMBSTICK_LEFT_HASH")	
#define VK_GAMEPAD_RIGHT_THUMBSTICK_UP_HASH		HASH("VK_GAMEPAD_RIGHT_THUMBSTICK_UP_HASH")		
#define VK_GAMEPAD_RIGHT_THUMBSTICK_DOWN_HASH	HASH("VK_GAMEPAD_RIGHT_THUMBSTICK_DOWN_HASH")	
#define VK_GAMEPAD_RIGHT_THUMBSTICK_RIGHT_HASH	HASH("VK_GAMEPAD_RIGHT_THUMBSTICK_RIGHT_HASH")	
#define VK_GAMEPAD_RIGHT_THUMBSTICK_LEFT_HASH	HASH("VK_GAMEPAD_RIGHT_THUMBSTICK_LEFT_HASH")	
#define VK_OEM_4_HASH							HASH("VK_OEM_4_HASH")							
#define VK_OEM_5_HASH							HASH("VK_OEM_5_HASH")							
#define VK_OEM_6_HASH							HASH("VK_OEM_6_HASH")							
#define VK_OEM_7_HASH							HASH("VK_OEM_7_HASH")							
#define VK_OEM_8_HASH							HASH("VK_OEM_8_HASH")							
#define VK_OEM_AX_HASH							HASH("VK_OEM_AX_HASH")							
#define VK_OEM_102_HASH							HASH("VK_OEM_102_HASH")							
#define VK_ICO_HELP_HASH						HASH("VK_ICO_HELP_HASH")						
#define VK_ICO_00_HASH							HASH("VK_ICO_00_HASH")							
#define VK_PROCESSKEY_HASH						HASH("VK_PROCESSKEY_HASH")						
#define VK_ICO_CLEAR_HASH						HASH("VK_ICO_CLEAR_HASH")						
#define VK_PACKET_HASH							HASH("VK_PACKET_HASH")							
#define VK_OEM_RESET_HASH						HASH("VK_OEM_RESET_HASH")						
#define VK_OEM_JUMP_HASH						HASH("VK_OEM_JUMP_HASH")						
#define VK_OEM_PA1_HASH							HASH("VK_OEM_PA1_HASH")							
#define VK_OEM_PA2_HASH							HASH("VK_OEM_PA2_HASH")							
#define VK_OEM_PA3_HASH							HASH("VK_OEM_PA3_HASH")							
#define VK_OEM_WSCTRL_HASH						HASH("VK_OEM_WSCTRL_HASH")						
#define VK_OEM_CUSEL_HASH						HASH("VK_OEM_CUSEL_HASH")						
#define VK_OEM_ATTN_HASH						HASH("VK_OEM_ATTN_HASH")						
#define VK_OEM_FINISH_HASH						HASH("VK_OEM_FINISH_HASH")						
#define VK_OEM_COPY_HASH						HASH("VK_OEM_COPY_HASH")						
#define VK_OEM_AUTO_HASH						HASH("VK_OEM_AUTO_HASH")						
#define VK_OEM_ENLW_HASH						HASH("VK_OEM_ENLW_HASH")						
#define VK_OEM_BACKTAB_HASH						HASH("VK_OEM_BACKTAB_HASH")						
#define VK_ATTN_HASH							HASH("VK_ATTN_HASH")							
#define VK_CRSEL_HASH							HASH("VK_CRSEL_HASH")							
#define VK_EXSEL_HASH							HASH("VK_EXSEL_HASH")							
#define VK_EREOF_HASH							HASH("VK_EREOF_HASH")							
#define VK_PLAY_HASH							HASH("VK_PLAY_HASH")							
#define VK_ZOOM_HASH							HASH("VK_ZOOM_HASH")							
#define VK_NONAME_HASH							HASH("VK_NONAME_HASH")							
#define VK_PA1_HASH								HASH("VK_PA1_HASH")								
#define VK_OEM_CLEAR_HASH						HASH("VK_OEM_CLEAR_HASH")								


unsigned char ConvertVKNameToValue(char* name)
{
	for (int i = 0; i<strlen(name); ++i)
		name[i] = toupper(name[i]);

	switch (bStringHash(name))
	{
	case VK_LBUTTON_HASH:
		return VK_LBUTTON;
	case VK_RBUTTON_HASH:
		return VK_RBUTTON;
	case VK_CANCEL_HASH:
		return VK_CANCEL;
	case VK_MBUTTON_HASH:
		return VK_MBUTTON;
	case VK_XBUTTON1_HASH:
		return VK_XBUTTON1;
	case VK_XBUTTON2_HASH:
		return VK_XBUTTON2;
	case VK_BACK_HASH:
		return VK_BACK;
	case VK_TAB_HASH:
		return VK_TAB;
	case VK_CLEAR_HASH:
		return VK_CLEAR;
	case VK_RETURN_HASH:
		return VK_RETURN;
	case VK_SHIFT_HASH:
		return VK_SHIFT;
	case VK_CONTROL_HASH:
		return VK_CONTROL;
	case VK_MENU_HASH:
		return VK_MENU;
	case VK_PAUSE_HASH:
		return VK_PAUSE;
	case VK_CAPITAL_HASH:
		return VK_CAPITAL;
	case VK_KANA_HASH:
		return VK_KANA;
	case VK_HANGEUL_HASH:
		return VK_HANGEUL;
	case VK_HANGUL_HASH:
		return VK_HANGUL;
	case VK_IME_ON_HASH:
		return VK_IME_ON;
	case VK_JUNJA_HASH:
		return VK_JUNJA;
	case VK_FINAL_HASH:
		return VK_FINAL;
	case VK_HANJA_HASH:
		return VK_HANJA;
	case VK_KANJI_HASH:
		return VK_KANJI;
	case VK_IME_OFF_HASH:
		return VK_IME_OFF;
	case VK_ESCAPE_HASH:
		return VK_ESCAPE;
	case VK_CONVERT_HASH:
		return VK_CONVERT;
	case VK_NONCONVERT_HASH:
		return VK_NONCONVERT;
	case VK_ACCEPT_HASH:
		return VK_ACCEPT;
	case VK_MODECHANGE_HASH:
		return VK_MODECHANGE;
	case VK_SPACE_HASH:
		return VK_SPACE;
	case VK_PRIOR_HASH:
		return VK_PRIOR;
	case VK_NEXT_HASH:
		return VK_NEXT;
	case VK_END_HASH:
		return VK_END;
	case VK_HOME_HASH:
		return VK_HOME;
	case VK_LEFT_HASH:
		return VK_LEFT;
	case VK_UP_HASH:
		return VK_UP;
	case VK_RIGHT_HASH:
		return VK_RIGHT;
	case VK_DOWN_HASH:
		return VK_DOWN;
	case VK_SELECT_HASH:
		return VK_SELECT;
	case VK_PRINT_HASH:
		return VK_PRINT;
	case VK_EXECUTE_HASH:
		return VK_EXECUTE;
	case VK_SNAPSHOT_HASH:
		return VK_SNAPSHOT;
	case VK_INSERT_HASH:
		return VK_INSERT;
	case VK_DELETE_HASH:
		return VK_DELETE;
	case VK_HELP_HASH:
		return VK_HELP;
	case VK_LWIN_HASH:
		return VK_LWIN;
	case VK_RWIN_HASH:
		return VK_RWIN;
	case VK_APPS_HASH:
		return VK_APPS;
	case VK_SLEEP_HASH:
		return VK_SLEEP;
	case VK_NUMPAD0_HASH:
		return VK_NUMPAD0;
	case VK_NUMPAD1_HASH:
		return VK_NUMPAD1;
	case VK_NUMPAD2_HASH:
		return VK_NUMPAD2;
	case VK_NUMPAD3_HASH:
		return VK_NUMPAD3;
	case VK_NUMPAD4_HASH:
		return VK_NUMPAD4;
	case VK_NUMPAD5_HASH:
		return VK_NUMPAD5;
	case VK_NUMPAD6_HASH:
		return VK_NUMPAD6;
	case VK_NUMPAD7_HASH:
		return VK_NUMPAD7;
	case VK_NUMPAD8_HASH:
		return VK_NUMPAD8;
	case VK_NUMPAD9_HASH:
		return VK_NUMPAD9;
	case VK_MULTIPLY_HASH:
		return VK_MULTIPLY;
	case VK_ADD_HASH:
		return VK_ADD;
	case VK_SEPARATOR_HASH:
		return VK_SEPARATOR;
	case VK_SUBTRACT_HASH:
		return VK_SUBTRACT;
	case VK_DECIMAL_HASH:
		return VK_DECIMAL;
	case VK_DIVIDE_HASH:
		return VK_DIVIDE;
	case VK_F1_HASH:
		return VK_F1;
	case VK_F2_HASH:
		return VK_F2;
	case VK_F3_HASH:
		return VK_F3;
	case VK_F4_HASH:
		return VK_F4;
	case VK_F5_HASH:
		return VK_F5;
	case VK_F6_HASH:
		return VK_F6;
	case VK_F7_HASH:
		return VK_F7;
	case VK_F8_HASH:
		return VK_F8;
	case VK_F9_HASH:
		return VK_F9;
	case VK_F10_HASH:
		return VK_F10;
	case VK_F11_HASH:
		return VK_F11;
	case VK_F12_HASH:
		return VK_F12;
	case VK_F13_HASH:
		return VK_F13;
	case VK_F14_HASH:
		return VK_F14;
	case VK_F15_HASH:
		return VK_F15;
	case VK_F16_HASH:
		return VK_F16;
	case VK_F17_HASH:
		return VK_F17;
	case VK_F18_HASH:
		return VK_F18;
	case VK_F19_HASH:
		return VK_F19;
	case VK_F20_HASH:
		return VK_F20;
	case VK_F21_HASH:
		return VK_F21;
	case VK_F22_HASH:
		return VK_F22;
	case VK_F23_HASH:
		return VK_F23;
	case VK_F24_HASH:
		return VK_F24;
	case VK_NAVIGATION_VIEW_HASH:
		return VK_NAVIGATION_VIEW;
	case VK_NAVIGATION_MENU_HASH:
		return VK_NAVIGATION_MENU;
	case VK_NAVIGATION_UP_HASH:
		return VK_NAVIGATION_UP;
	case VK_NAVIGATION_DOWN_HASH:
		return VK_NAVIGATION_DOWN;
	case VK_NAVIGATION_LEFT_HASH:
		return VK_NAVIGATION_LEFT;
	case VK_NAVIGATION_RIGHT_HASH:
		return VK_NAVIGATION_RIGHT;
	case VK_NAVIGATION_ACCEPT_HASH:
		return VK_NAVIGATION_ACCEPT;
	case VK_NAVIGATION_CANCEL_HASH:
		return VK_NAVIGATION_CANCEL;
	case VK_NUMLOCK_HASH:
		return VK_NUMLOCK;
	case VK_SCROLL_HASH:
		return VK_SCROLL;
	case VK_OEM_NEC_EQUAL_HASH:
		return VK_OEM_NEC_EQUAL;
	case VK_OEM_FJ_JISHO_HASH:
		return VK_OEM_FJ_JISHO;
	case VK_OEM_FJ_MASSHOU_HASH:
		return VK_OEM_FJ_MASSHOU;
	case VK_OEM_FJ_TOUROKU_HASH:
		return VK_OEM_FJ_TOUROKU;
	case VK_OEM_FJ_LOYA_HASH:
		return VK_OEM_FJ_LOYA;
	case VK_OEM_FJ_ROYA_HASH:
		return VK_OEM_FJ_ROYA;
	case VK_LSHIFT_HASH:
		return VK_LSHIFT;
	case VK_RSHIFT_HASH:
		return VK_RSHIFT;
	case VK_LCONTROL_HASH:
		return VK_LCONTROL;
	case VK_RCONTROL_HASH:
		return VK_RCONTROL;
	case VK_LMENU_HASH:
		return VK_LMENU;
	case VK_RMENU_HASH:
		return VK_RMENU;
	case VK_BROWSER_BACK_HASH:
		return VK_BROWSER_BACK;
	case VK_BROWSER_FORWARD_HASH:
		return VK_BROWSER_FORWARD;
	case VK_BROWSER_REFRESH_HASH:
		return VK_BROWSER_REFRESH;
	case VK_BROWSER_STOP_HASH:
		return VK_BROWSER_STOP;
	case VK_BROWSER_SEARCH_HASH:
		return VK_BROWSER_SEARCH;
	case VK_BROWSER_FAVORITES_HASH:
		return VK_BROWSER_FAVORITES;
	case VK_BROWSER_HOME_HASH:
		return VK_BROWSER_HOME;
	case VK_VOLUME_MUTE_HASH:
		return VK_VOLUME_MUTE;
	case VK_VOLUME_DOWN_HASH:
		return VK_VOLUME_DOWN;
	case VK_VOLUME_UP_HASH:
		return VK_VOLUME_UP;
	case VK_MEDIA_NEXT_TRACK_HASH:
		return VK_MEDIA_NEXT_TRACK;
	case VK_MEDIA_PREV_TRACK_HASH:
		return VK_MEDIA_PREV_TRACK;
	case VK_MEDIA_STOP_HASH:
		return VK_MEDIA_STOP;
	case VK_MEDIA_PLAY_PAUSE_HASH:
		return VK_MEDIA_PLAY_PAUSE;
	case VK_LAUNCH_MAIL_HASH:
		return VK_LAUNCH_MAIL;
	case VK_LAUNCH_MEDIA_SELECT_HASH:
		return VK_LAUNCH_MEDIA_SELECT;
	case VK_LAUNCH_APP1_HASH:
		return VK_LAUNCH_APP1;
	case VK_LAUNCH_APP2_HASH:
		return VK_LAUNCH_APP2;
	case VK_OEM_1_HASH:
		return VK_OEM_1;
	case VK_OEM_PLUS_HASH:
		return VK_OEM_PLUS;
	case VK_OEM_COMMA_HASH:
		return VK_OEM_COMMA;
	case VK_OEM_MINUS_HASH:
		return VK_OEM_MINUS;
	case VK_OEM_PERIOD_HASH:
		return VK_OEM_PERIOD;
	case VK_OEM_2_HASH:
		return VK_OEM_2;
	case VK_OEM_3_HASH:
		return VK_OEM_3;
	case VK_GAMEPAD_A_HASH:
		return VK_GAMEPAD_A;
	case VK_GAMEPAD_B_HASH:
		return VK_GAMEPAD_B;
	case VK_GAMEPAD_X_HASH:
		return VK_GAMEPAD_X;
	case VK_GAMEPAD_Y_HASH:
		return VK_GAMEPAD_Y;
	case VK_GAMEPAD_RIGHT_SHOULDER_HASH:
		return VK_GAMEPAD_RIGHT_SHOULDER;
	case VK_GAMEPAD_LEFT_SHOULDER_HASH:
		return VK_GAMEPAD_LEFT_SHOULDER;
	case VK_GAMEPAD_LEFT_TRIGGER_HASH:
		return VK_GAMEPAD_LEFT_TRIGGER;
	case VK_GAMEPAD_RIGHT_TRIGGER_HASH:
		return VK_GAMEPAD_RIGHT_TRIGGER;
	case VK_GAMEPAD_DPAD_UP_HASH:
		return VK_GAMEPAD_DPAD_UP;
	case VK_GAMEPAD_DPAD_DOWN_HASH:
		return VK_GAMEPAD_DPAD_DOWN;
	case VK_GAMEPAD_DPAD_LEFT_HASH:
		return VK_GAMEPAD_DPAD_LEFT;
	case VK_GAMEPAD_DPAD_RIGHT_HASH:
		return VK_GAMEPAD_DPAD_RIGHT;
	case VK_GAMEPAD_MENU_HASH:
		return VK_GAMEPAD_MENU;
	case VK_GAMEPAD_VIEW_HASH:
		return VK_GAMEPAD_VIEW;
	case VK_GAMEPAD_LEFT_THUMBSTICK_BUTTON_HASH:
		return VK_GAMEPAD_LEFT_THUMBSTICK_BUTTON;
	case VK_GAMEPAD_RIGHT_THUMBSTICK_BUTTON_HASH:
		return VK_GAMEPAD_RIGHT_THUMBSTICK_BUTTON;
	case VK_GAMEPAD_LEFT_THUMBSTICK_UP_HASH:
		return VK_GAMEPAD_LEFT_THUMBSTICK_UP;
	case VK_GAMEPAD_LEFT_THUMBSTICK_DOWN_HASH:
		return VK_GAMEPAD_LEFT_THUMBSTICK_DOWN;
	case VK_GAMEPAD_LEFT_THUMBSTICK_RIGHT_HASH:
		return VK_GAMEPAD_LEFT_THUMBSTICK_RIGHT;
	case VK_GAMEPAD_LEFT_THUMBSTICK_LEFT_HASH:
		return VK_GAMEPAD_LEFT_THUMBSTICK_LEFT;
	case VK_GAMEPAD_RIGHT_THUMBSTICK_UP_HASH:
		return VK_GAMEPAD_RIGHT_THUMBSTICK_UP;
	case VK_GAMEPAD_RIGHT_THUMBSTICK_DOWN_HASH:
		return VK_GAMEPAD_RIGHT_THUMBSTICK_DOWN;
	case VK_GAMEPAD_RIGHT_THUMBSTICK_RIGHT_HASH:
		return VK_GAMEPAD_RIGHT_THUMBSTICK_RIGHT;
	case VK_GAMEPAD_RIGHT_THUMBSTICK_LEFT_HASH:
		return VK_GAMEPAD_RIGHT_THUMBSTICK_LEFT;
	case VK_OEM_4_HASH:
		return VK_OEM_4;
	case VK_OEM_5_HASH:
		return VK_OEM_5;
	case VK_OEM_6_HASH:
		return VK_OEM_6;
	case VK_OEM_7_HASH:
		return VK_OEM_7;
	case VK_OEM_8_HASH:
		return VK_OEM_8;
	case VK_OEM_AX_HASH:
		return VK_OEM_AX;
	case VK_OEM_102_HASH:
		return VK_OEM_102;
	case VK_ICO_HELP_HASH:
		return VK_ICO_HELP;
	case VK_ICO_00_HASH:
		return VK_ICO_00;
	case VK_PROCESSKEY_HASH:
		return VK_PROCESSKEY;
	case VK_ICO_CLEAR_HASH:
		return VK_ICO_CLEAR;
	case VK_PACKET_HASH:
		return VK_PACKET;
	case VK_OEM_RESET_HASH:
		return VK_OEM_RESET;
	case VK_OEM_JUMP_HASH:
		return VK_OEM_JUMP;
	case VK_OEM_PA1_HASH:
		return VK_OEM_PA1;
	case VK_OEM_PA2_HASH:
		return VK_OEM_PA2;
	case VK_OEM_PA3_HASH:
		return VK_OEM_PA3;
	case VK_OEM_WSCTRL_HASH:
		return VK_OEM_WSCTRL;
	case VK_OEM_CUSEL_HASH:
		return VK_OEM_CUSEL;
	case VK_OEM_ATTN_HASH:
		return VK_OEM_ATTN;
	case VK_OEM_FINISH_HASH:
		return VK_OEM_FINISH;
	case VK_OEM_COPY_HASH:
		return VK_OEM_COPY;
	case VK_OEM_AUTO_HASH:
		return VK_OEM_AUTO;
	case VK_OEM_ENLW_HASH:
		return VK_OEM_ENLW;
	case VK_OEM_BACKTAB_HASH:
		return VK_OEM_BACKTAB;
	case VK_ATTN_HASH:
		return VK_ATTN;
	case VK_CRSEL_HASH:
		return VK_CRSEL;
	case VK_EXSEL_HASH:
		return VK_EXSEL;
	case VK_EREOF_HASH:
		return VK_EREOF;
	case VK_PLAY_HASH:
		return VK_PLAY;
	case VK_ZOOM_HASH:
		return VK_ZOOM;
	case VK_NONAME_HASH:
		return VK_NONAME;
	case VK_PA1_HASH:
		return VK_PA1;
	case VK_OEM_CLEAR_HASH:
		return VK_OEM_CLEAR;

	default:
		break;
	}
	return 0;
}
