#pragma once
#include <string.h>

unsigned int sub_5CC090(char* a1, int a2, unsigned int a3)
{
	unsigned int v4; // eax
	unsigned int v5; // ecx
	unsigned int v6; // ebp
	int v7; // edi
	unsigned int v9; // edx
	unsigned int v10; // ecx
	unsigned int v11; // esi
	int v12; // eax
	unsigned int v13; // ecx
	unsigned int v14; // esi
	int v15; // eax
	unsigned int v16; // ecx
	unsigned int v17; // esi
	unsigned int v18; // esi
	int v19; // edi
	unsigned int v20; // ecx
	unsigned int v21; // esi
	int v22; // edi
	unsigned int v23; // ecx
	unsigned int v24; // esi
	int v25; // edi

	v4 = a3;
	v5 = 0x9E3779B9;
	v6 = a3;
	v7 = 0x9E3779B9;
	if (a3 >= 0xC)
	{
		v9 = a3 / 0xC;
		do
		{
			v10 = *((int*)a1 + 1) + v5;
			v11 = *((int*)a1 + 2) + a2;
			v12 = (v11 >> 13) ^ (v7 + *(int*)a1 - v11 - v10);
			v13 = (v12 << 8) ^ (v10 - v11 - v12);
			v14 = (v13 >> 13) ^ (v11 - v13 - v12);
			v15 = (v14 >> 12) ^ (v12 - v14 - v13);
			v16 = (v15 << 16) ^ (v13 - v14 - v15);
			v17 = (v16 >> 5) ^ (v14 - v16 - v15);
			v7 = (v17 >> 3) ^ (v15 - v17 - v16);
			v5 = (v7 << 10) ^ (v16 - v17 - v7);
			a2 = (v5 >> 15) ^ (v17 - v5 - v7);
			a1 += 12;
			v6 -= 12;
			--v9;
		} while (v9);
		v4 = a3;
	}
	v18 = v4 + a2;
	switch (v6)
	{
	case 11:
		v18 += a1[10] << 24;
	case 10:
		v18 += a1[9] << 16;
	case 9:
		v18 += a1[8] << 8;
	case 8:
		v5 += a1[7] << 24;
	case 7:
		v5 += a1[6] << 16;
	case 6:
		v5 += a1[5] << 8;
	case 5:
		v5 += a1[4];
	case 4:
		v7 += a1[3] << 24;
	case 3:
		v7 += a1[2] << 16;
	case 2:
		v7 += a1[1] << 8;
	case 1:
		v7 += *a1;
		break;
	default:
		break;
	}

	v19 = (v18 >> 13) ^ (v7 - v18 - v5);
	v20 = (v19 << 8) ^ (v5 - v18 - v19);
	v21 = (v20 >> 13) ^ (v18 - v20 - v19);
	v22 = (v21 >> 12) ^ (v19 - v21 - v20);
	v23 = (v22 << 16) ^ (v20 - v21 - v22);
	v24 = (v23 >> 5) ^ (v21 - v23 - v22);
	v25 = (v24 >> 3) ^ (v22 - v24 - v23);
	return (((v25 << 10) ^ (v23 - v24 - v25)) >> 15) ^ (v24 - ((v25 << 10) ^ (v23 - v24 - v25)) - v25);
}

unsigned int stringhash32(char* a1)
{
	unsigned int result; // eax

	if (a1 && *a1)
		result = sub_5CC090(a1, 0xABCDEF00, strlen(a1));
	else
		result = 0;
	return result;
}

#ifdef GAME_MW
enum ActionID
{
	NULL_ACTION = 0,
	GAMEACTION_STEERLEFT = 1,
	GAMEACTION_STEERRIGHT = 2,
	GAMEACTION_TURNLEFT = 3,
	GAMEACTION_TURNRIGHT = 4,
	GAMEACTION_GAS = 5,
	GAMEACTION_BRAKE = 6,
	GAMEACTION_HANDBRAKE = 7,
	GAMEACTION_GAMEBREAKER = 8,
	GAMEACTION_SHIFTUP = 9,
	GAMEACTION_SHIFTDOWN = 10,
	GAMEACTION_NOS = 11,
	GAMEACTION_RESET = 12,
	GAMEACTION_FORWARD = 13,
	GAMEACTION_BACK = 14,
	GAMEACTION_JUMP = 15,
	GAMEACTION_DEBUGHUMAN1 = 16,
	GAMEACTION_DEBUGHUMAN2 = 17,
	GAMEACTION_DEBUGHUMAN3 = 18,
	GAMEACTION_DEBUGHUMAN4 = 19,
	CAMERAACTION_CHANGE = 20,
	CAMERAACTION_DEBUG = 21,
	CAMERAACTION_ENABLE_ICE = 22,
	CAMERAACTION_LOOKBACK = 23,
	CAMERAACTION_PULLBACK = 24,
	FRONTENDACTION_UP = 25,
	FRONTENDACTION_DOWN = 26,
	FRONTENDACTION_LEFT = 27,
	FRONTENDACTION_RIGHT = 28,
	FRONTENDACTION_RUP = 29,
	FRONTENDACTION_RDOWN = 30,
	FRONTENDACTION_RLEFT = 31,
	FRONTENDACTION_RRIGHT = 32,
	FRONTENDACTION_ACCEPT = 33,
	FRONTENDACTION_CANCEL = 34,
	FRONTENDACTION_CANCEL_ALT = 35,
	FRONTENDACTION_START = 36,
	FRONTENDACTION_BUTTON0 = 37,
	FRONTENDACTION_BUTTON1 = 38,
	FRONTENDACTION_BUTTON2 = 39,
	FRONTENDACTION_BUTTON3 = 40,
	FRONTENDACTION_BUTTON4 = 41,
	FRONTENDACTION_BUTTON5 = 42,
	FRONTENDACTION_LTRIGGER = 43,
	FRONTENDACTION_RTRIGGER = 44,
	HUDACTION_PAUSEREQUEST = 45,
	HUDACTION_ENGAGE_EVENT = 46,
	HUDACTION_PAD_LEFT = 47,
	HUDACTION_PAD_DOWN = 48,
	HUDACTION_PAD_RIGHT = 49,
	HUDACTION_SKIPNIS = 50,
	HUDACTION_NEXTSONG = 51,
	VOIPACTION_PUSHTOTALK = 52,
	DEBUGACTION_MOVE_UP = 53,
	DEBUGACTION_MOVE_DOWN = 54,
	DEBUGACTION_MOVE_LEFT = 55,
	DEBUGACTION_MOVE_RIGHT = 56,
	DEBUGACTION_MOVE_FORWARD = 57,
	DEBUGACTION_MOVE_BACK = 58,
	DEBUGACTION_MOVE_D_LEFT = 59,
	DEBUGACTION_MOVE_D_RIGHT = 60,
	DEBUGACTION_MOVE_D_FORWARD = 61,
	DEBUGACTION_MOVE_D_BACK = 62,
	DEBUGACTION_LOOK_UP = 63,
	DEBUGACTION_LOOK_DOWN = 64,
	DEBUGACTION_LOOK_LEFT = 65,
	DEBUGACTION_LOOK_RIGHT = 66,
	DEBUGACTION_LOOK_D_UP = 67,
	DEBUGACTION_LOOK_D_DOWN = 68,
	DEBUGACTION_LOOK_D_LEFT = 69,
	DEBUGACTION_LOOK_D_RIGHT = 70,
	DEBUGACTION_TURBO = 71,
	DEBUGACTION_SUPER_TURBO = 72,
	DEBUGACTION_DROPCAR = 73,
	DEBUGACTION_TOGGLEAI = 74,
	DEBUGACTION_TOGGLESIMSTEP = 75,
	DEBUGACTION_SIMSTEP = 76,
	DEBUGACTION_SCREENSHOT = 77,
	DEBUGACTION_STOPRECORDPATH = 78,
	DEBUGACTION_TOGGLECARCOLOUR = 79,
	DEBUGACTION_TOGGLEDEMOCAMERAS = 80,
	ICEACTION_GRAB_LEFT = 81,
	ICEACTION_GRAB_RIGHT = 82,
	ICEACTION_LEFT = 83,
	ICEACTION_RIGHT = 84,
	ICEACTION_FAST_LEFT = 85,
	ICEACTION_FAST_RIGHT = 86,
	ICEACTION_UP = 87,
	ICEACTION_DOWN = 88,
	ICEACTION_HELP = 89,
	ICEACTION_UNDO = 90,
	ICEACTION_PLAY = 91,
	ICEACTION_HIDE = 92,
	ICEACTION_SCREENSHOT = 93,
	ICEACTION_SCREENSHOT_STREAM = 94,
	ICEACTION_INSERT = 95,
	ICEACTION_CUT = 96,
	ICEACTION_COPY = 97,
	ICEACTION_PASTE = 98,
	ICEACTION_SELECT = 99,
	ICEACTION_CANCEL = 100,
	ICEACTION_ALT_1 = 101,
	ICEACTION_CLIP_IN = 102,
	ICEACTION_CLIP_OUT = 103,
	ICEACTION_SIMSPEED_INC = 104,
	ICEACTION_SIMSPEED_DEC = 105,
	ICEACTION_DUTCH_LEFT = 106,
	ICEACTION_DUTCH_RIGHT = 107,
	ICEACTION_ZOOM_IN = 108,
	ICEACTION_ZOOM_OUT = 109,
	ICEACTION_LETTERBOX_IN = 110,
	ICEACTION_LETTERBOX_OUT = 111,
	ICEACTION_BUBBLE_IN = 112,
	ICEACTION_BUBBLE_OUT = 113,
	ICEACTION_BUBBLE_UP = 114,
	ICEACTION_BUBBLE_DOWN = 115,
	ICEACTION_BUBBLE_TILT_UP = 116,
	ICEACTION_BUBBLE_TILT_DOWN = 117,
	ICEACTION_BUBBLE_SPIN_LEFT = 118,
	ICEACTION_BUBBLE_SPIN_RIGHT = 119,
	ICEACTION_BUBBLE_LEFT = 120,
	ICEACTION_BUBBLE_RIGHT = 121,
	ICEACTION_BUBBLE_BACK = 122,
	ICEACTION_BUBBLE_FORTH = 123,
	ICEACTION_SHAKE_MAG_DEC = 124,
	ICEACTION_SHAKE_MAG_INC = 125,
	ICEACTION_SHAKE_FRQ_DEC = 126,
	ICEACTION_SHAKE_FRQ_INC = 127,
	ICEACTION_SHUTTLE_LEFT = 128,
	ICEACTION_SHUTTLE_RIGHT = 129,
	ICEACTION_SHUTTLE_UP = 130,
	ICEACTION_SHUTTLE_DOWN = 131,
	ICEACTION_SHUTTLE_SPEED_DEC = 132,
	ICEACTION_SHUTTLE_SPEED_INC = 133,
	ACTION_EXITAPPLICATION = 134,
	ACTION_PLUGGED = 135,
	ACTION_UNPLUGGED = 136,
	ACTION_FLUSH = 137,
	MAX_ACTIONID = 138,
};

char ActionIDStr[139][32] =
{
"NULL_ACTION",
"GAMEACTION_STEERLEFT",
"GAMEACTION_STEERRIGHT",
"GAMEACTION_TURNLEFT",
"GAMEACTION_TURNRIGHT",
"GAMEACTION_GAS",
"GAMEACTION_BRAKE",
"GAMEACTION_HANDBRAKE",
"GAMEACTION_GAMEBREAKER",
"GAMEACTION_SHIFTUP",
"GAMEACTION_SHIFTDOWN",
"GAMEACTION_NOS",
"GAMEACTION_RESET",
"GAMEACTION_FORWARD",
"GAMEACTION_BACK",
"GAMEACTION_JUMP",
"GAMEACTION_DEBUGHUMAN1",
"GAMEACTION_DEBUGHUMAN2",
"GAMEACTION_DEBUGHUMAN3",
"GAMEACTION_DEBUGHUMAN4",
"CAMERAACTION_CHANGE",
"CAMERAACTION_DEBUG",
"CAMERAACTION_ENABLE_ICE",
"CAMERAACTION_LOOKBACK",
"CAMERAACTION_PULLBACK",
"FRONTENDACTION_UP",
"FRONTENDACTION_DOWN",
"FRONTENDACTION_LEFT",
"FRONTENDACTION_RIGHT",
"FRONTENDACTION_RUP",
"FRONTENDACTION_RDOWN",
"FRONTENDACTION_RLEFT",
"FRONTENDACTION_RRIGHT",
"FRONTENDACTION_ACCEPT",
"FRONTENDACTION_CANCEL",
"FRONTENDACTION_CANCEL_ALT",
"FRONTENDACTION_START",
"FRONTENDACTION_BUTTON0",
"FRONTENDACTION_BUTTON1",
"FRONTENDACTION_BUTTON2",
"FRONTENDACTION_BUTTON3",
"FRONTENDACTION_BUTTON4",
"FRONTENDACTION_BUTTON5",
"FRONTENDACTION_LTRIGGER",
"FRONTENDACTION_RTRIGGER",
"HUDACTION_PAUSEREQUEST",
"HUDACTION_ENGAGE_EVENT",
"HUDACTION_PAD_LEFT",
"HUDACTION_PAD_DOWN",
"HUDACTION_PAD_RIGHT",
"HUDACTION_SKIPNIS",
"HUDACTION_NEXTSONG",
"VOIPACTION_PUSHTOTALK",
"DEBUGACTION_MOVE_UP",
"DEBUGACTION_MOVE_DOWN",
"DEBUGACTION_MOVE_LEFT",
"DEBUGACTION_MOVE_RIGHT",
"DEBUGACTION_MOVE_FORWARD",
"DEBUGACTION_MOVE_BACK",
"DEBUGACTION_MOVE_D_LEFT",
"DEBUGACTION_MOVE_D_RIGHT",
"DEBUGACTION_MOVE_D_FORWARD",
"DEBUGACTION_MOVE_D_BACK",
"DEBUGACTION_LOOK_UP",
"DEBUGACTION_LOOK_DOWN",
"DEBUGACTION_LOOK_LEFT",
"DEBUGACTION_LOOK_RIGHT",
"DEBUGACTION_LOOK_D_UP",
"DEBUGACTION_LOOK_D_DOWN",
"DEBUGACTION_LOOK_D_LEFT",
"DEBUGACTION_LOOK_D_RIGHT",
"DEBUGACTION_TURBO",
"DEBUGACTION_SUPER_TURBO",
"DEBUGACTION_DROPCAR",
"DEBUGACTION_TOGGLEAI",
"DEBUGACTION_TOGGLESIMSTEP",
"DEBUGACTION_SIMSTEP",
"DEBUGACTION_SCREENSHOT",
"DEBUGACTION_STOPRECORDPATH",
"DEBUGACTION_TOGGLECARCOLOUR",
"DEBUGACTION_TOGGLEDEMOCAMERAS",
"ICEACTION_GRAB_LEFT",
"ICEACTION_GRAB_RIGHT",
"ICEACTION_LEFT",
"ICEACTION_RIGHT",
"ICEACTION_FAST_LEFT",
"ICEACTION_FAST_RIGHT",
"ICEACTION_UP",
"ICEACTION_DOWN",
"ICEACTION_HELP",
"ICEACTION_UNDO",
"ICEACTION_PLAY",
"ICEACTION_HIDE",
"ICEACTION_SCREENSHOT",
"ICEACTION_SCREENSHOT_STREAM",
"ICEACTION_INSERT",
"ICEACTION_CUT",
"ICEACTION_COPY",
"ICEACTION_PASTE",
"ICEACTION_SELECT",
"ICEACTION_CANCEL",
"ICEACTION_ALT_1",
"ICEACTION_CLIP_IN",
"ICEACTION_CLIP_OUT",
"ICEACTION_SIMSPEED_INC",
"ICEACTION_SIMSPEED_DEC",
"ICEACTION_DUTCH_LEFT",
"ICEACTION_DUTCH_RIGHT",
"ICEACTION_ZOOM_IN",
"ICEACTION_ZOOM_OUT",
"ICEACTION_LETTERBOX_IN",
"ICEACTION_LETTERBOX_OUT",
"ICEACTION_BUBBLE_IN",
"ICEACTION_BUBBLE_OUT",
"ICEACTION_BUBBLE_UP",
"ICEACTION_BUBBLE_DOWN",
"ICEACTION_BUBBLE_TILT_UP",
"ICEACTION_BUBBLE_TILT_DOWN",
"ICEACTION_BUBBLE_SPIN_LEFT",
"ICEACTION_BUBBLE_SPIN_RIGHT",
"ICEACTION_BUBBLE_LEFT",
"ICEACTION_BUBBLE_RIGHT",
"ICEACTION_BUBBLE_BACK",
"ICEACTION_BUBBLE_FORTH",
"ICEACTION_SHAKE_MAG_DEC",
"ICEACTION_SHAKE_MAG_INC",
"ICEACTION_SHAKE_FRQ_DEC",
"ICEACTION_SHAKE_FRQ_INC",
"ICEACTION_SHUTTLE_LEFT",
"ICEACTION_SHUTTLE_RIGHT",
"ICEACTION_SHUTTLE_UP",
"ICEACTION_SHUTTLE_DOWN",
"ICEACTION_SHUTTLE_SPEED_DEC",
"ICEACTION_SHUTTLE_SPEED_INC",
"ACTION_EXITAPPLICATION",
"ACTION_PLUGGED",
"ACTION_UNPLUGGED",
"ACTION_FLUSH",
"MAX_ACTIONID"
};

#endif

#ifdef GAME_CARBON
enum ActionID
{
	NULL_ACTION = 0,
	GAMEACTION_STEERLEFT = 1,
	GAMEACTION_STEERRIGHT = 2,
	GAMEACTION_OVERSTEER = 3,
	GAMEACTION_OVERSTEERLEFT = 4,
	GAMEACTION_OVERSTEERRIGHT = 5,
	GAMEACTION_TURNLEFT = 6,
	GAMEACTION_TURNRIGHT = 7,
	GAMEACTION_GAS = 8,
	GAMEACTION_BRAKE = 9,
	GAMEACTION_HANDBRAKE = 10,
	GAMEACTION_GAMEBREAKER = 11,
	GAMEACTION_SHIFTUP = 12,
	GAMEACTION_SHIFTDOWN = 13,
	GAMEACTION_SHIFTFIRST = 14,
	GAMEACTION_SHIFTSECOND = 15,
	GAMEACTION_SHIFTTHIRD = 16,
	GAMEACTION_SHIFTFOURTH = 17,
	GAMEACTION_SHIFTFIFTH = 18,
	GAMEACTION_SHIFTSIXTH = 19,
	GAMEACTION_SHIFTNEUTRAL = 20,
	GAMEACTION_SHIFTREVERSE = 21,
	GAMEACTION_NOS = 22,
	GAMEACTION_RESET = 23,
	GAMEACTION_CREWAGGRESSIVE = 24,
	GAMEACTION_CREWDEFENSIVE = 25,
	GAMEACTION_CREWDEFAULT = 26,
	GAMEACTION_CREWSPEED = 27,
	GAMEACTION_FORWARD = 28,
	GAMEACTION_BACK = 29,
	GAMEACTION_JUMP = 30,
	GAMEACTION_DEBUGHUMAN1 = 31,
	GAMEACTION_DEBUGHUMAN2 = 32,
	GAMEACTION_DEBUGHUMAN3 = 33,
	GAMEACTION_DEBUGHUMAN4 = 34,
	GAMEACTION_CLUTCH = 35,
	CAMERAACTION_CHANGE = 36,
	CAMERAACTION_DEBUG = 37,
	CAMERAACTION_ENABLE_ICE = 38,
	CAMERAACTION_LOOKBACK = 39,
	CAMERAACTION_PULLBACK = 40,
	FRONTENDACTION_UP = 41,
	FRONTENDACTION_DOWN = 42,
	FRONTENDACTION_LEFT = 43,
	FRONTENDACTION_RIGHT = 44,
	FRONTENDACTION_RUP = 45,
	FRONTENDACTION_RDOWN = 46,
	FRONTENDACTION_RLEFT = 47,
	FRONTENDACTION_RRIGHT = 48,
	FRONTENDACTION_ACCEPT = 49,
	FRONTENDACTION_CANCEL = 50,
	FRONTENDACTION_CANCEL_ALT = 51,
	FRONTENDACTION_START = 52,
	FRONTENDACTION_BUTTON0 = 53,
	FRONTENDACTION_BUTTON1 = 54,
	FRONTENDACTION_BUTTON2 = 55,
	FRONTENDACTION_BUTTON3 = 56,
	FRONTENDACTION_BUTTON4 = 57,
	FRONTENDACTION_BUTTON5 = 58,
	FRONTENDACTION_LTRIGGER = 59,
	FRONTENDACTION_RTRIGGER = 60,
	HUDACTION_PAUSEREQUEST = 61,
	HUDACTION_ENGAGE_EVENT = 62,
	HUDACTION_PAD_LEFT = 63,
	HUDACTION_PAD_DOWN = 64,
	HUDACTION_PAD_RIGHT = 65,
	HUDACTION_SKIPNIS = 66,
	HUDACTION_NEXTSONG = 67,
	HUDACTION_VOIPACTIVATION = 68,
	HUDACTION_VOIPDEACTIVATION = 69,
	VOIPACTION_PUSHTOTALK = 70,
	DEBUGACTION_MOVE_UP = 71,
	DEBUGACTION_MOVE_DOWN = 72,
	DEBUGACTION_MOVE_LEFT = 73,
	DEBUGACTION_MOVE_RIGHT = 74,
	DEBUGACTION_MOVE_FORWARD = 75,
	DEBUGACTION_MOVE_BACK = 76,
	DEBUGACTION_MOVE_D_LEFT = 77,
	DEBUGACTION_MOVE_D_RIGHT = 78,
	DEBUGACTION_MOVE_D_FORWARD = 79,
	DEBUGACTION_MOVE_D_BACK = 80,
	DEBUGACTION_LOOK_UP = 81,
	DEBUGACTION_LOOK_DOWN = 82,
	DEBUGACTION_LOOK_LEFT = 83,
	DEBUGACTION_LOOK_RIGHT = 84,
	DEBUGACTION_LOOK_D_UP = 85,
	DEBUGACTION_LOOK_D_DOWN = 86,
	DEBUGACTION_LOOK_D_LEFT = 87,
	DEBUGACTION_LOOK_D_RIGHT = 88,
	DEBUGACTION_TURBO = 89,
	DEBUGACTION_SUPER_TURBO = 90,
	DEBUGACTION_DROPCAR = 91,
	DEBUGACTION_TOGGLEAI = 92,
	DEBUGACTION_TOGGLESIMSTEP = 93,
	DEBUGACTION_SIMSTEP = 94,
	DEBUGACTION_SCREENSHOT = 95,
	DEBUGACTION_STOPRECORDPATH = 96,
	DEBUGACTION_TOGGLECARCOLOUR = 97,
	DEBUGACTION_TOGGLEDEMOCAMERAS = 98,
	ACTION_EXITAPPLICATION = 136,
	ACTION_PLUGGED = 137,
	ACTION_UNPLUGGED = 138,
	ACTION_FLUSH = 139,
	MAX_ACTIONID
};

char ActionIDStr[MAX_ACTIONID][32] =
{
	"NULL_ACTION",
	"GAMEACTION_STEERLEFT",
	"GAMEACTION_STEERRIGHT",
	"GAMEACTION_OVERSTEER",
	"GAMEACTION_OVERSTEERLEFT",
	"GAMEACTION_OVERSTEERRIGHT",
	"GAMEACTION_TURNLEFT",
	"GAMEACTION_TURNRIGHT",
	"GAMEACTION_GAS",
	"GAMEACTION_BRAKE",
	"GAMEACTION_HANDBRAKE",
	"GAMEACTION_GAMEBREAKER",
	"GAMEACTION_SHIFTUP",
	"GAMEACTION_SHIFTDOWN",
	"GAMEACTION_SHIFTFIRST",
	"GAMEACTION_SHIFTSECOND",
	"GAMEACTION_SHIFTTHIRD",
	"GAMEACTION_SHIFTFOURTH",
	"GAMEACTION_SHIFTFIFTH",
	"GAMEACTION_SHIFTSIXTH",
	"GAMEACTION_SHIFTNEUTRAL",
	"GAMEACTION_SHIFTREVERSE",
	"GAMEACTION_NOS",
	"GAMEACTION_RESET",
	"GAMEACTION_CREWAGGRESSIVE",
	"GAMEACTION_CREWDEFENSIVE",
	"GAMEACTION_CREWDEFAULT",
	"GAMEACTION_CREWSPEED",
	"GAMEACTION_FORWARD",
	"GAMEACTION_BACK",
	"GAMEACTION_JUMP",
	"GAMEACTION_DEBUGHUMAN1",
	"GAMEACTION_DEBUGHUMAN2",
	"GAMEACTION_DEBUGHUMAN3",
	"GAMEACTION_DEBUGHUMAN4",
	"GAMEACTION_CLUTCH",
	"CAMERAACTION_CHANGE",
	"CAMERAACTION_DEBUG",
	"CAMERAACTION_ENABLE_ICE",
	"CAMERAACTION_LOOKBACK",
	"CAMERAACTION_PULLBACK",
	"FRONTENDACTION_UP",
	"FRONTENDACTION_DOWN",
	"FRONTENDACTION_LEFT",
	"FRONTENDACTION_RIGHT",
	"FRONTENDACTION_RUP",
	"FRONTENDACTION_RDOWN",
	"FRONTENDACTION_RLEFT",
	"FRONTENDACTION_RRIGHT",
	"FRONTENDACTION_ACCEPT",
	"FRONTENDACTION_CANCEL",
	"FRONTENDACTION_CANCEL_ALT",
	"FRONTENDACTION_START",
	"FRONTENDACTION_BUTTON0",
	"FRONTENDACTION_BUTTON1",
	"FRONTENDACTION_BUTTON2",
	"FRONTENDACTION_BUTTON3",
	"FRONTENDACTION_BUTTON4",
	"FRONTENDACTION_BUTTON5",
	"FRONTENDACTION_LTRIGGER",
	"FRONTENDACTION_RTRIGGER",
	"HUDACTION_PAUSEREQUEST",
	"HUDACTION_ENGAGE_EVENT",
	"HUDACTION_PAD_LEFT",
	"HUDACTION_PAD_DOWN",
	"HUDACTION_PAD_RIGHT",
	"HUDACTION_SKIPNIS",
	"HUDACTION_NEXTSONG",
	"HUDACTION_VOIPACTIVATION",
	"HUDACTION_VOIPDEACTIVATION",
	"VOIPACTION_PUSHTOTALK",
	"DEBUGACTION_MOVE_UP",
	"DEBUGACTION_MOVE_DOWN",
	"DEBUGACTION_MOVE_LEFT",
	"DEBUGACTION_MOVE_RIGHT",
	"DEBUGACTION_MOVE_FORWARD",
	"DEBUGACTION_MOVE_BACK",
	"DEBUGACTION_MOVE_D_LEFT",
	"DEBUGACTION_MOVE_D_RIGHT",
	"DEBUGACTION_MOVE_D_FORWARD",
	"DEBUGACTION_MOVE_D_BACK",
	"DEBUGACTION_LOOK_UP",
	"DEBUGACTION_LOOK_DOWN",
	"DEBUGACTION_LOOK_LEFT",
	"DEBUGACTION_LOOK_RIGHT",
	"DEBUGACTION_LOOK_D_UP",
	"DEBUGACTION_LOOK_D_DOWN",
	"DEBUGACTION_LOOK_D_LEFT",
	"DEBUGACTION_LOOK_D_RIGHT",
	"DEBUGACTION_TURBO",
	"DEBUGACTION_SUPER_TURBO",
	"DEBUGACTION_DROPCAR",
	"DEBUGACTION_TOGGLEAI",
	"DEBUGACTION_TOGGLESIMSTEP",
	"DEBUGACTION_SIMSTEP",
	"DEBUGACTION_SCREENSHOT",
	"DEBUGACTION_STOPRECORDPATH",
	"DEBUGACTION_TOGGLECARCOLOUR",
	"DEBUGACTION_TOGGLEDEMOCAMERAS",
	"ACTION_EXITAPPLICATION",
	"ACTION_PLUGGED",
	"ACTION_UNPLUGGED",
	"ACTION_FLUSH"
};
#endif

#define NULL_ACTION_HASH 0x97310EE9
#define GAMEACTION_STEERLEFT_HASH 0x37B1B6A8
#define GAMEACTION_STEERRIGHT_HASH 0xB3A37C41
#define GAMEACTION_OVERSTEER_HASH 0x14462292
#define GAMEACTION_OVERSTEERLEFT_HASH 0x281F5607
#define GAMEACTION_OVERSTEERRIGHT_HASH 0x960A8C59
#define GAMEACTION_TURNLEFT_HASH 0x77570455
#define GAMEACTION_TURNRIGHT_HASH 0xFA647F8F
#define GAMEACTION_GAS_HASH 0x6525329
#define GAMEACTION_GAS_SLOTCAR_HASH 0x18FB8E6
#define GAMEACTION_BRAKE_HASH 0x82A9B7D8
#define GAMEACTION_HANDBRAKE_HASH 0x1AAF2C13
#define GAMEACTION_GAMEBREAKER_HASH 0x98D605B8
#define GAMEACTION_SHIFTUP_HASH 0x6DBD3C3
#define GAMEACTION_SHIFTDOWN_HASH 0x50638735
#define GAMEACTION_SHIFTFIRST_HASH 0xCDA5DCEA
#define GAMEACTION_SHIFTSECOND_HASH 0x78E2FEE8
#define GAMEACTION_SHIFTTHIRD_HASH 0xBE5E63AD
#define GAMEACTION_SHIFTFOURTH_HASH 0xC7380B94
#define GAMEACTION_SHIFTFIFTH_HASH 0x5AF6F41C
#define GAMEACTION_SHIFTSIXTH_HASH 0x60889606
#define GAMEACTION_SHIFTNEUTRAL_HASH 0x343EC7F0
#define GAMEACTION_SHIFTREVERSE_HASH 0x15731650
#define GAMEACTION_NOS_HASH 0xABC46A0F
#define GAMEACTION_RESET_HASH 0xB488445A
#define GAMEACTION_CREWAGGRESSIVE_HASH 0xF3F8558F
#define GAMEACTION_CREWDEFENSIVE_HASH 0x434446BE
#define GAMEACTION_CREWDEFAULT_HASH 0x86185D5C
#define GAMEACTION_CREWSPEED_HASH 0x97CDC0D1
#define GAMEACTION_FORWARD_HASH 0xDC1AB9EA
#define GAMEACTION_BACK_HASH 0xDC0E7B73
#define GAMEACTION_JUMP_HASH 0xBA48A502
#define GAMEACTION_DEBUGHUMAN1_HASH 0xE82D180F
#define GAMEACTION_DEBUGHUMAN2_HASH 0x37EB8EA4
#define GAMEACTION_DEBUGHUMAN3_HASH 0x15024C88
#define GAMEACTION_DEBUGHUMAN4_HASH 0x6B76F3BE
#define GAMEACTION_CLUTCH_HASH 0x13C8B320
#define GAMEACTION_CLUTCH_KICK_HASH 0xCDEB6B0D
#define CAMERAACTION_CHANGE_HASH 0x2F478795
#define CAMERAACTION_DEBUG_HASH 0xACC223C6
#define CAMERAACTION_ENABLE_ICE_HASH 0xBAC6C7D7
#define CAMERAACTION_LOOKBACK_HASH 0x8DC18FAF
#define CAMERAACTION_PULLBACK_HASH 0x7F189EEC
#define CAMERAACTION_ROT_LEFT_HASH 0xB794CD40
#define CAMERAACTION_ROT_RIGHT_HASH 0x2C41C1FA
#define CAMERAACTION_360_HASH 0xB35CE4AA
#define FRONTENDACTION_UP_HASH 0xC455D61D
#define FRONTENDACTION_DOWN_HASH 0xEF3FAC67
#define FRONTENDACTION_LEFT_HASH 0x97011FC1
#define FRONTENDACTION_RIGHT_HASH 0xA968B63A
#define FRONTENDACTION_RUP_HASH 0x2B8B4B6F
#define FRONTENDACTION_RDOWN_HASH 0x6645BD6
#define FRONTENDACTION_RLEFT_HASH 0x376803FA
#define FRONTENDACTION_RRIGHT_HASH 0xDE24DF25
#define FRONTENDACTION_ACCEPT_HASH 0xC18193FD
#define FRONTENDACTION_CANCEL_HASH 0x1079014
#define FRONTENDACTION_CANCEL_ALT_HASH 0xF6E6BAD9
#define FRONTENDACTION_START_HASH 0x67EEBE3F
#define FRONTENDACTION_BUTTON0_HASH 0x6EB8DEDC
#define FRONTENDACTION_BUTTON1_HASH 0x5954D9C3
#define FRONTENDACTION_BUTTON2_HASH 0x2C68D30
#define FRONTENDACTION_BUTTON3_HASH 0x4178FC35
#define FRONTENDACTION_BUTTON4_HASH 0xF31F71C7
#define FRONTENDACTION_BUTTON5_HASH 0xA28033B2
#define FRONTENDACTION_LTRIGGER_HASH 0xEDA51002
#define FRONTENDACTION_RTRIGGER_HASH 0x8D005B54
#define HUDACTION_PAUSEREQUEST_HASH 0xDAAF60CD
#define HUDACTION_ENGAGE_EVENT_HASH 0xBBAB56EF
#define HUDACTION_PAD_LEFT_HASH 0xE2D51BDC
#define HUDACTION_PAD_DOWN_HASH 0x112B5D2D
#define HUDACTION_PAD_RIGHT_HASH 0x713C8F5C
#define HUDACTION_SKIPNIS_HASH 0x8053361A
#define HUDACTION_NEXTSONG_HASH 0x5A1E0EB7
#define HUDACTION_VOIPACTIVATION_HASH 0x5BBF311C
#define HUDACTION_VOIPDEACTIVATION_HASH 0xA8DC8F7E
#define HUDACTION_TOGGLE_LEADERBOARD_HASH 0xCE2C0C1F
#define HUDACTION_TOGGLE_MINIMAP_HASH 0xD3F00DFA
#define HUDACTION_TOGGLE_BESTLINE_HASH 0x5E39D962
#define HUDACTION_TOGGLE_ARROWS_HASH 0x4AC162AD
#define VOIPACTION_PUSHTOTALK_HASH 0xE5C50A17
#define DEBUGACTION_MOVE_UP_HASH 0x65F33C23
#define DEBUGACTION_MOVE_DOWN_HASH 0x5EB6F87F
#define DEBUGACTION_MOVE_LEFT_HASH 0x98A510C3
#define DEBUGACTION_MOVE_RIGHT_HASH 0x64A558DE
#define DEBUGACTION_MOVE_FORWARD_HASH 0x3391934B
#define DEBUGACTION_MOVE_BACK_HASH 0xB9DB7418
#define DEBUGACTION_MOVE_D_LEFT_HASH 0x3AE35A4C
#define DEBUGACTION_MOVE_D_RIGHT_HASH 0xA449A027
#define DEBUGACTION_MOVE_D_FORWARD_HASH 0x76354CB7
#define DEBUGACTION_MOVE_D_BACK_HASH 0x94227BAD
#define DEBUGACTION_LOOK_UP_HASH 0xC0C95361
#define DEBUGACTION_LOOK_DOWN_HASH 0x136435AC
#define DEBUGACTION_LOOK_LEFT_HASH 0x8AFCED7A
#define DEBUGACTION_LOOK_RIGHT_HASH 0x5C36897F
#define DEBUGACTION_LOOK_D_UP_HASH 0x8BB25BD4
#define DEBUGACTION_LOOK_D_DOWN_HASH 0x88E9F301
#define DEBUGACTION_LOOK_D_LEFT_HASH 0xF3C5ED4E
#define DEBUGACTION_LOOK_D_RIGHT_HASH 0x49EADE84
#define DEBUGACTION_TURBO_HASH 0x2CF3D7D7
#define DEBUGACTION_SUPER_TURBO_HASH 0x7D1B500D
#define DEBUGACTION_DROPCAR_HASH 0xBDF62D8E
#define DEBUGACTION_TOGGLEAI_HASH 0x1FF07AEF
#define DEBUGACTION_TOGGLESIMSTEP_HASH 0x770E0D16
#define DEBUGACTION_SIMSTEP_HASH 0x1F903FEC
#define DEBUGACTION_SCREENSHOT_HASH 0xEA8F77F6
#define DEBUGACTION_STOPRECORDPATH_HASH 0xF57F6CAD
#define DEBUGACTION_TOGGLECARCOLOUR_HASH 0x25E38FDF
#define DEBUGACTION_TOGGLEDEMOCAMERAS_HASH 0xEDD2A2F3
#define ICEACTION_GRAB_LEFT_HASH 0xD6D7FB4
#define ICEACTION_GRAB_RIGHT_HASH 0xFCBD5969
#define ICEACTION_LEFT_HASH 0xEB1CE242
#define ICEACTION_RIGHT_HASH 0x5BD28819
#define ICEACTION_FAST_LEFT_HASH 0x21ECBBA
#define ICEACTION_FAST_RIGHT_HASH 0x1CF73674
#define ICEACTION_UP_HASH 0x5383ADEA
#define ICEACTION_DOWN_HASH 0x80FF983C
#define ICEACTION_HELP_HASH 0xCBB4CCBF
#define ICEACTION_UNDO_HASH 0xC9ACA929
#define ICEACTION_PLAY_HASH 0x5404DD6D
#define ICEACTION_HIDE_HASH 0x9B1E3F1B
#define ICEACTION_SCREENSHOT_HASH 0x68AF00CB
#define ICEACTION_SCREENSHOT_STREAM_HASH 0x915B5E15
#define ICEACTION_INSERT_HASH 0xBEC5A35
#define ICEACTION_CUT_HASH 0x7BE61732
#define ICEACTION_COPY_HASH 0x469A29A2
#define ICEACTION_PASTE_HASH 0xCF996F30
#define ICEACTION_SELECT_HASH 0xA3B4828B
#define ICEACTION_CANCEL_HASH 0xD9E3873B
#define ICEACTION_ALT_1_HASH 0xC6658AEF
#define ICEACTION_CLIP_IN_HASH 0x85C7F9FF
#define ICEACTION_CLIP_OUT_HASH 0xA4F85F2D
#define ICEACTION_SIMSPEED_INC_HASH 0x25EE8E66
#define ICEACTION_SIMSPEED_DEC_HASH 0xB5625552
#define ICEACTION_DUTCH_LEFT_HASH 0x34E03ED7
#define ICEACTION_DUTCH_RIGHT_HASH 0x5F9D1D
#define ICEACTION_ZOOM_IN_HASH 0x46B49ED9
#define ICEACTION_ZOOM_OUT_HASH 0xF036026A
#define ICEACTION_LETTERBOX_IN_HASH 0x509346CD
#define ICEACTION_LETTERBOX_OUT_HASH 0x9D6DEA3C
#define ICEACTION_BUBBLE_IN_HASH 0x71E24C87
#define ICEACTION_BUBBLE_OUT_HASH 0x535F828A
#define ICEACTION_BUBBLE_UP_HASH 0xFD8110F
#define ICEACTION_BUBBLE_DOWN_HASH 0x8573245A
#define ICEACTION_BUBBLE_TILT_UP_HASH 0x2CFDF83B
#define ICEACTION_BUBBLE_TILT_DOWN_HASH 0x58482016
#define ICEACTION_BUBBLE_SPIN_LEFT_HASH 0x5BCD578B
#define ICEACTION_BUBBLE_SPIN_RIGHT_HASH 0x8784BB00
#define ICEACTION_BUBBLE_LEFT_HASH 0x83D67A7B
#define ICEACTION_BUBBLE_RIGHT_HASH 0xDD43339A
#define ICEACTION_BUBBLE_BACK_HASH 0x90B590F9
#define ICEACTION_BUBBLE_FORTH_HASH 0xC667A7C0
#define ICEACTION_SHAKE_MAG_DEC_HASH 0x8A9EE6EF
#define ICEACTION_SHAKE_MAG_INC_HASH 0xDA3FA888
#define ICEACTION_SHAKE_FRQ_DEC_HASH 0x68306931
#define ICEACTION_SHAKE_FRQ_INC_HASH 0xD3F858CA
#define ICEACTION_SHUTTLE_LEFT_HASH 0x9B870F45
#define ICEACTION_SHUTTLE_RIGHT_HASH 0x591CF93A
#define ICEACTION_SHUTTLE_UP_HASH 0xDCFE9685
#define ICEACTION_SHUTTLE_DOWN_HASH 0xDC4CCB3C
#define ICEACTION_SHUTTLE_SPEED_DEC_HASH 0xF08628DE
#define ICEACTION_SHUTTLE_SPEED_INC_HASH 0x82FD8328
#define ICE_ACTION_START_HASH 0x4E26E3C0
#define ICE_ACTION_SELECT_HASH 0x169E703B
#define ICE_ACTION_SOUTH_HASH 0x4D750674
#define ICE_ACTION_SOUTH_PRESS_HASH 0xB3616AF6
#define ICE_ACTION_NORTH_HASH 0xD8D19B3
#define ICE_ACTION_NORTH_PRESS_HASH 0xF671DD60
#define ICE_ACTION_WEST_HASH 0x2129D8C0
#define ICE_ACTION_WEST_PRESS_HASH 0xF6186D65
#define ICE_ACTION_EAST_HASH 0xCDFD6E83
#define ICE_ACTION_EAST_PRESS_HASH 0x9E6F50DF
#define ICE_ACTION_DOWN_HASH 0xA6A26111
#define ICE_ACTION_DOWN_PRESS_HASH 0x514851DC
#define ICE_ACTION_UP_HASH 0x65BB8EDE
#define ICE_ACTION_UP_PRESS_HASH 0xD4422301
#define ICE_ACTION_LEFT_HASH 0x6D47C591
#define ICE_ACTION_LEFT_PRESS_HASH 0x54E208CF
#define ICE_ACTION_RIGHT_HASH 0x832AE86A
#define ICE_ACTION_RIGHT_PRESS_HASH 0x2A32E20
#define ICE_ACTION_L1_HASH 0x13F967B2
#define ICE_ACTION_L1_PRESS_HASH 0x3A3ABB74
#define ICE_ACTION_R1_HASH 0x88B2F408
#define ICE_ACTION_R1_PRESS_HASH 0xC934591D
#define ICE_ACTION_L2_HASH 0x109B8009
#define ICE_ACTION_L2_PRESS_HASH 0xECCF12EE
#define ICE_ACTION_R2_HASH 0xA838547C
#define ICE_ACTION_R2_PRESS_HASH 0xCC881D97
#define ICE_ACTION_L3_HASH 0x353144B1
#define ICE_ACTION_L3_PRESS_HASH 0xBA9FAA1E
#define ICE_ACTION_R3_HASH 0x9B745627
#define ICE_ACTION_R3_RELEASE_HASH 0x3E32F5C2
#define ICE_ACTION_LEFTSTICK_LEFT_HASH 0xF4D57C4E
#define ICE_ACTION_LEFTSTICK_RIGHT_HASH 0xAFCFD341
#define ICE_ACTION_LEFTSTICK_DOWN_HASH 0x6620548A
#define ICE_ACTION_LEFTSTICK_UP_HASH 0x151FC37
#define ICE_ACTION_RIGHTSTICK_LEFT_HASH 0xCD710A96
#define ICE_ACTION_RIGHTSTICK_RIGHT_HASH 0x33CE0C95
#define ICE_ACTION_RIGHTSTICK_DOWN_HASH 0xFDF95CD
#define ICE_ACTION_RIGHTSTICK_UP_HASH 0xB14B2E9D
#define ACTION_EXITAPPLICATION_HASH 0x1E427936
#define ACTION_PLUGGED_HASH 0xED30E410
#define ACTION_UNPLUGGED_HASH 0xEE7DA1F4
#define ACTION_FLUSH_HASH 0x7314C969
#define GAME_ACTION_GAS_HASH 0x2B469B7A
#define GAME_ACTION_BRAKE_HASH 0x82E09967
#define GAME_ACTION_STEERLEFT_HASH 0x10C7B791
#define GAME_ACTION_STEERRIGHT_HASH 0x53184B6
#define GAME_ACTION_HANDBRAKE_HASH 0x33AC4319
#define GAME_ACTION_GAMEBREAKER_HASH 0x1A9D1D39
#define GAME_ACTION_NOS_HASH 0x1E0E19FC
#define GAME_ACTION_SHIFTDOWN_HASH 0x7D890353
#define GAME_ACTION_SHIFTUP_HASH 0x699F04CE
#define GAME_ACTION_RESET_HASH 0xD80AF964
#define FE_ACTION_B2_HASH 0x15C8ADF5
#define CAM_ACTION_CHANGE_HASH 0x61777C3
#define CAM_ACTION_LOOKBACK_HASH 0x67120AC0
#define CAM_ACTION_PULLBACK_HASH 0x4785E830
#define FE_ACTION_LEFT_HASH 0x69CAB6A5
#define FE_ACTION_RIGHT_HASH 0x6653BDAC
#define FE_ACTION_UP_HASH 0xFC3B2126
#define FE_ACTION_DOWN_HASH 0x274B6C12
#define SC_W_HASH 0x2D309C2B
#define SC_A_HASH 0x91A21CC2
#define SC_S_HASH 0x342D0496
#define SC_D_HASH 0x29C49335
#define FE_ACTION_RTRIGGER_HASH 0xD3EAC352
#define FE_ACTION_LTRIGGER_HASH 0xDBFAA03A
#define SC_BACKSLASH_HASH 0x94B23C23
#define FE_ACTION_ACCEPT_HASH 0x5B037F12
#define FE_ACTION_CANCEL_HASH 0x1CCB6B91
#define FE_ACTION_START_HASH 0x4B32A0B2
#define FE_ACTION_LTRIG_HASH 0x74B77A36
#define FE_ACTION_RTRIG_HASH 0x2C017F46
#define FE_ACTION_B0_HASH 0xD197D33F
#define FE_ACTION_B1_HASH 0xA2E6E03A
#define FE_ACTION_B3_HASH 0x7343D94C
#define FE_ACTION_B4_HASH 0x3BB77AB5
#define FE_ACTION_B5_HASH 0x7D09C7C2
#define SC_Z_HASH 0xC644D7D4
#define SC_X_HASH 0x31C006E8
#define SC_C_HASH 0x3F717709
#define SC_V_HASH 0x14623752
#define SC_F1_HASH 0x35FFAB2D
#define SC_MINUS_HASH 0xF2C2D411
#define SC_EQUALS_HASH 0x9511DE32
#define SC_LBRACKET_HASH 0x71DB3D06
#define SC_RBRACKET_HASH 0xE6702EE3
#define SC_LALT_HASH 0xAFBB6CB0
#define SC_RALT_HASH 0x9F34B6D1
#define SC_NUMPADENTER_HASH 0x1563B02B
#define SC_PAGEUP_HASH 0xF3E85904
#define SC_PAGEDOWN_HASH 0x8DA95293
#define SC_RETURN_HASH 0xE2B4228A
#define SC_ESCAPE_HASH 0x6EF54B9B
#define SC_SPACE_HASH 0xBF1C3C5A
#define SC_INSERT_HASH 0xDB541D0D
#define SC_BACK_HASH 0xF85A0B60
#define SC_NUMPAD1_HASH 0x1AE4D555
#define SC_NUMPAD2_HASH 0xCEC2BC5E
#define SC_NUMPAD3_HASH 0x1B1DBAD7
#define SC_NUMPAD4_HASH 0x433ABF5C
#define SC_NUMPAD5_HASH 0x552A3F25
#define SC_NUMPAD6_HASH 0x40A12463
#define SC_NUMPAD7_HASH 0xCBB1D47D
#define SC_NUMPAD8_HASH 0x7A0B6887
#define SC_NUMPAD9_HASH 0xE29643E3
#define SC_NUMPAD0_HASH 0x3FAD8E05
#define SC_DECIMAL_HASH 0xFFE78245
#define SC_SUBTRACT_HASH 0xD05E508A
#define SC_ADD_HASH 0x754DCD5B
#define MAX_ACTIONID_HASH 0x4014F20F

// secondary bind names
#define FE_SECONDARY_UP_NAME "FRONTENDACTION_UP_ALT"
#define FE_SECONDARY_DOWN_NAME "FRONTENDACTION_DOWN_ALT"
#define FE_SECONDARY_LEFT_NAME "FRONTENDACTION_LEFT_ALT"
#define FE_SECONDARY_RIGHT_NAME "FRONTENDACTION_RIGHT_ALT"

ActionID ConvertStringToActionID(char* name)
{
	switch (stringhash32(name))
	{
	case NULL_ACTION_HASH:
		return NULL_ACTION;
	case GAMEACTION_STEERLEFT_HASH:
		return GAMEACTION_STEERLEFT;
	case GAMEACTION_STEERRIGHT_HASH:
		return GAMEACTION_STEERRIGHT;
	case GAMEACTION_TURNLEFT_HASH:
		return GAMEACTION_TURNLEFT;
	case GAMEACTION_TURNRIGHT_HASH:
		return GAMEACTION_TURNRIGHT;
	case GAMEACTION_GAS_HASH:
		return GAMEACTION_GAS;
	case GAMEACTION_BRAKE_HASH:
		return GAMEACTION_BRAKE;
	case GAMEACTION_HANDBRAKE_HASH:
		return GAMEACTION_HANDBRAKE;
	case GAMEACTION_GAMEBREAKER_HASH:
		return GAMEACTION_GAMEBREAKER;
	case GAMEACTION_SHIFTUP_HASH:
		return GAMEACTION_SHIFTUP;
	case GAMEACTION_SHIFTDOWN_HASH:
		return GAMEACTION_SHIFTDOWN;
	case GAMEACTION_NOS_HASH:
		return GAMEACTION_NOS;
	case GAMEACTION_RESET_HASH:
		return GAMEACTION_RESET;
	case GAMEACTION_FORWARD_HASH:
		return GAMEACTION_FORWARD;
	case GAMEACTION_BACK_HASH:
		return GAMEACTION_BACK;
	case GAMEACTION_JUMP_HASH:
		return GAMEACTION_JUMP;
	case GAMEACTION_DEBUGHUMAN1_HASH:
		return GAMEACTION_DEBUGHUMAN1;
	case GAMEACTION_DEBUGHUMAN2_HASH:
		return GAMEACTION_DEBUGHUMAN2;
	case GAMEACTION_DEBUGHUMAN3_HASH:
		return GAMEACTION_DEBUGHUMAN3;
	case GAMEACTION_DEBUGHUMAN4_HASH:
		return GAMEACTION_DEBUGHUMAN4;
	case CAMERAACTION_CHANGE_HASH:
		return CAMERAACTION_CHANGE;
	case CAMERAACTION_DEBUG_HASH:
		return CAMERAACTION_DEBUG;
	case CAMERAACTION_ENABLE_ICE_HASH:
		return CAMERAACTION_ENABLE_ICE;
	case CAMERAACTION_LOOKBACK_HASH:
		return CAMERAACTION_LOOKBACK;
	case CAMERAACTION_PULLBACK_HASH:
		return CAMERAACTION_PULLBACK;
	case FRONTENDACTION_UP_HASH:
		return FRONTENDACTION_UP;
	case FRONTENDACTION_DOWN_HASH:
		return FRONTENDACTION_DOWN;
	case FRONTENDACTION_LEFT_HASH:
		return FRONTENDACTION_LEFT;
	case FRONTENDACTION_RIGHT_HASH:
		return FRONTENDACTION_RIGHT;
	case FRONTENDACTION_RUP_HASH:
		return FRONTENDACTION_RUP;
	case FRONTENDACTION_RDOWN_HASH:
		return FRONTENDACTION_RDOWN;
	case FRONTENDACTION_RLEFT_HASH:
		return FRONTENDACTION_RLEFT;
	case FRONTENDACTION_RRIGHT_HASH:
		return FRONTENDACTION_RRIGHT;
	case FRONTENDACTION_ACCEPT_HASH:
		return FRONTENDACTION_ACCEPT;
	case FRONTENDACTION_CANCEL_HASH:
		return FRONTENDACTION_CANCEL;
	case FRONTENDACTION_CANCEL_ALT_HASH:
		return FRONTENDACTION_CANCEL_ALT;
	case FRONTENDACTION_START_HASH:
		return FRONTENDACTION_START;
	case FRONTENDACTION_BUTTON0_HASH:
		return FRONTENDACTION_BUTTON0;
	case FRONTENDACTION_BUTTON1_HASH:
		return FRONTENDACTION_BUTTON1;
	case FRONTENDACTION_BUTTON2_HASH:
		return FRONTENDACTION_BUTTON2;
	case FRONTENDACTION_BUTTON3_HASH:
		return FRONTENDACTION_BUTTON3;
	case FRONTENDACTION_BUTTON4_HASH:
		return FRONTENDACTION_BUTTON4;
	case FRONTENDACTION_BUTTON5_HASH:
		return FRONTENDACTION_BUTTON5;
	case FRONTENDACTION_LTRIGGER_HASH:
		return FRONTENDACTION_LTRIGGER;
	case FRONTENDACTION_RTRIGGER_HASH:
		return FRONTENDACTION_RTRIGGER;
	case HUDACTION_PAUSEREQUEST_HASH:
		return HUDACTION_PAUSEREQUEST;
	case HUDACTION_ENGAGE_EVENT_HASH:
		return HUDACTION_ENGAGE_EVENT;
	case HUDACTION_PAD_LEFT_HASH:
		return HUDACTION_PAD_LEFT;
	case HUDACTION_PAD_DOWN_HASH:
		return HUDACTION_PAD_DOWN;
	case HUDACTION_PAD_RIGHT_HASH:
		return HUDACTION_PAD_RIGHT;
	case HUDACTION_SKIPNIS_HASH:
		return HUDACTION_SKIPNIS;
	case HUDACTION_NEXTSONG_HASH:
		return HUDACTION_NEXTSONG;
	case VOIPACTION_PUSHTOTALK_HASH:
		return VOIPACTION_PUSHTOTALK;
	case DEBUGACTION_MOVE_UP_HASH:
		return DEBUGACTION_MOVE_UP;
	case DEBUGACTION_MOVE_DOWN_HASH:
		return DEBUGACTION_MOVE_DOWN;
	case DEBUGACTION_MOVE_LEFT_HASH:
		return DEBUGACTION_MOVE_LEFT;
	case DEBUGACTION_MOVE_RIGHT_HASH:
		return DEBUGACTION_MOVE_RIGHT;
	case DEBUGACTION_MOVE_FORWARD_HASH:
		return DEBUGACTION_MOVE_FORWARD;
	case DEBUGACTION_MOVE_BACK_HASH:
		return DEBUGACTION_MOVE_BACK;
	case DEBUGACTION_MOVE_D_LEFT_HASH:
		return DEBUGACTION_MOVE_D_LEFT;
	case DEBUGACTION_MOVE_D_RIGHT_HASH:
		return DEBUGACTION_MOVE_D_RIGHT;
	case DEBUGACTION_MOVE_D_FORWARD_HASH:
		return DEBUGACTION_MOVE_D_FORWARD;
	case DEBUGACTION_MOVE_D_BACK_HASH:
		return DEBUGACTION_MOVE_D_BACK;
	case DEBUGACTION_LOOK_UP_HASH:
		return DEBUGACTION_LOOK_UP;
	case DEBUGACTION_LOOK_DOWN_HASH:
		return DEBUGACTION_LOOK_DOWN;
	case DEBUGACTION_LOOK_LEFT_HASH:
		return DEBUGACTION_LOOK_LEFT;
	case DEBUGACTION_LOOK_RIGHT_HASH:
		return DEBUGACTION_LOOK_RIGHT;
	case DEBUGACTION_LOOK_D_UP_HASH:
		return DEBUGACTION_LOOK_D_UP;
	case DEBUGACTION_LOOK_D_DOWN_HASH:
		return DEBUGACTION_LOOK_D_DOWN;
	case DEBUGACTION_LOOK_D_LEFT_HASH:
		return DEBUGACTION_LOOK_D_LEFT;
	case DEBUGACTION_LOOK_D_RIGHT_HASH:
		return DEBUGACTION_LOOK_D_RIGHT;
	case DEBUGACTION_TURBO_HASH:
		return DEBUGACTION_TURBO;
	case DEBUGACTION_SUPER_TURBO_HASH:
		return DEBUGACTION_SUPER_TURBO;
	case DEBUGACTION_DROPCAR_HASH:
		return DEBUGACTION_DROPCAR;
	case DEBUGACTION_TOGGLEAI_HASH:
		return DEBUGACTION_TOGGLEAI;
	case DEBUGACTION_TOGGLESIMSTEP_HASH:
		return DEBUGACTION_TOGGLESIMSTEP;
	case DEBUGACTION_SIMSTEP_HASH:
		return DEBUGACTION_SIMSTEP;
	case DEBUGACTION_SCREENSHOT_HASH:
		return DEBUGACTION_SCREENSHOT;
	case DEBUGACTION_STOPRECORDPATH_HASH:
		return DEBUGACTION_STOPRECORDPATH;
	case DEBUGACTION_TOGGLECARCOLOUR_HASH:
		return DEBUGACTION_TOGGLECARCOLOUR;
	case DEBUGACTION_TOGGLEDEMOCAMERAS_HASH:
		return DEBUGACTION_TOGGLEDEMOCAMERAS;
	case ACTION_EXITAPPLICATION_HASH:
		return ACTION_EXITAPPLICATION;
	case ACTION_PLUGGED_HASH:
		return ACTION_PLUGGED;
	case ACTION_UNPLUGGED_HASH:
		return ACTION_UNPLUGGED;
	case ACTION_FLUSH_HASH:
		return ACTION_FLUSH;
#ifndef GAME_MW
	case GAMEACTION_OVERSTEER_HASH:
		return GAMEACTION_OVERSTEER;
	case GAMEACTION_OVERSTEERLEFT_HASH:
		return GAMEACTION_OVERSTEERLEFT;
	case GAMEACTION_OVERSTEERRIGHT_HASH:
		return GAMEACTION_OVERSTEERRIGHT;
	case GAMEACTION_SHIFTFIRST_HASH:
		return GAMEACTION_SHIFTFIRST;
	case GAMEACTION_SHIFTSECOND_HASH:
		return GAMEACTION_SHIFTSECOND;
	case GAMEACTION_SHIFTTHIRD_HASH:
		return GAMEACTION_SHIFTTHIRD;
	case GAMEACTION_SHIFTFOURTH_HASH:
		return GAMEACTION_SHIFTFOURTH;
	case GAMEACTION_SHIFTFIFTH_HASH:
		return GAMEACTION_SHIFTFIFTH;
	case GAMEACTION_SHIFTSIXTH_HASH:
		return GAMEACTION_SHIFTSIXTH;
	case GAMEACTION_SHIFTNEUTRAL_HASH:
		return GAMEACTION_SHIFTNEUTRAL;
	case GAMEACTION_SHIFTREVERSE_HASH:
		return GAMEACTION_SHIFTREVERSE;
	case GAMEACTION_CREWAGGRESSIVE_HASH:
		return GAMEACTION_CREWAGGRESSIVE;
	case GAMEACTION_CREWDEFENSIVE_HASH:
		return GAMEACTION_CREWDEFENSIVE;
	case GAMEACTION_CREWDEFAULT_HASH:
		return GAMEACTION_CREWDEFAULT;
	case GAMEACTION_CREWSPEED_HASH:
		return GAMEACTION_CREWSPEED;
	case GAMEACTION_CLUTCH_HASH:
		return GAMEACTION_CLUTCH;
	case HUDACTION_VOIPACTIVATION_HASH:
		return HUDACTION_VOIPACTIVATION;
	case HUDACTION_VOIPDEACTIVATION_HASH:
		return HUDACTION_VOIPDEACTIVATION;


#ifdef GAME_PROSTREET
	case GAMEACTION_CLUTCH_KICK_HASH:
		return GAMEACTION_CLUTCH_KICK;
	case CAMERAACTION_ROT_LEFT_HASH:
		return CAMERAACTION_ROT_LEFT;
	case CAMERAACTION_ROT_RIGHT_HASH:
		return CAMERAACTION_ROT_RIGHT;
	case CAMERAACTION_360_HASH:
		return CAMERAACTION_360;
	case HUDACTION_TOGGLE_LEADERBOARD_HASH:
		return HUDACTION_TOGGLE_LEADERBOARD;
	case HUDACTION_TOGGLE_MINIMAP_HASH:
		return HUDACTION_TOGGLE_MINIMAP;
	case HUDACTION_TOGGLE_BESTLINE_HASH:
		return HUDACTION_TOGGLE_BESTLINE;
	case HUDACTION_TOGGLE_ARROWS_HASH:
		return HUDACTION_TOGGLE_ARROWS;
#endif

#endif

#ifdef GAME_DEBUG_VERSION
	case GAMEACTION_GAS_SLOTCAR_HASH:
		return GAMEACTION_GAS_SLOTCAR;
	case ICE_ACTION_START_HASH:
		return ICE_ACTION_START;
	case ICE_ACTION_SELECT_HASH:
		return ICE_ACTION_SELECT;
	case ICE_ACTION_SOUTH_HASH:
		return ICE_ACTION_SOUTH;
	case ICE_ACTION_SOUTH_PRESS_HASH:
		return ICE_ACTION_SOUTH_PRESS;
	case ICE_ACTION_NORTH_HASH:
		return ICE_ACTION_NORTH;
	case ICE_ACTION_NORTH_PRESS_HASH:
		return ICE_ACTION_NORTH_PRESS;
	case ICE_ACTION_WEST_HASH:
		return ICE_ACTION_WEST;
	case ICE_ACTION_WEST_PRESS_HASH:
		return ICE_ACTION_WEST_PRESS;
	case ICE_ACTION_EAST_HASH:
		return ICE_ACTION_EAST;
	case ICE_ACTION_EAST_PRESS_HASH:
		return ICE_ACTION_EAST_PRESS;
	case ICE_ACTION_DOWN_HASH:
		return ICE_ACTION_DOWN;
	case ICE_ACTION_DOWN_PRESS_HASH:
		return ICE_ACTION_DOWN_PRESS;
	case ICE_ACTION_UP_HASH:
		return ICE_ACTION_UP;
	case ICE_ACTION_UP_PRESS_HASH:
		return ICE_ACTION_UP_PRESS;
	case ICE_ACTION_LEFT_HASH:
		return ICE_ACTION_LEFT;
	case ICE_ACTION_LEFT_PRESS_HASH:
		return ICE_ACTION_LEFT_PRESS;
	case ICE_ACTION_RIGHT_HASH:
		return ICE_ACTION_RIGHT;
	case ICE_ACTION_RIGHT_PRESS_HASH:
		return ICE_ACTION_RIGHT_PRESS;
	case ICE_ACTION_L1_HASH:
		return ICE_ACTION_L1;
	case ICE_ACTION_L1_PRESS_HASH:
		return ICE_ACTION_L1_PRESS;
	case ICE_ACTION_R1_HASH:
		return ICE_ACTION_R1;
	case ICE_ACTION_R1_PRESS_HASH:
		return ICE_ACTION_R1_PRESS;
	case ICE_ACTION_L2_HASH:
		return ICE_ACTION_L2;
	case ICE_ACTION_L2_PRESS_HASH:
		return ICE_ACTION_L2_PRESS;
	case ICE_ACTION_R2_HASH:
		return ICE_ACTION_R2;
	case ICE_ACTION_R2_PRESS_HASH:
		return ICE_ACTION_R2_PRESS;
	case ICE_ACTION_L3_HASH:
		return ICE_ACTION_L3;
	case ICE_ACTION_L3_PRESS_HASH:
		return ICE_ACTION_L3_PRESS;
	case ICE_ACTION_R3_HASH:
		return ICE_ACTION_R3;
	case ICE_ACTION_R3_RELEASE_HASH:
		return ICE_ACTION_R3_RELEASE;
	case ICE_ACTION_LEFTSTICK_LEFT_HASH:
		return ICE_ACTION_LEFTSTICK_LEFT;
	case ICE_ACTION_LEFTSTICK_RIGHT_HASH:
		return ICE_ACTION_LEFTSTICK_RIGHT;
	case ICE_ACTION_LEFTSTICK_DOWN_HASH:
		return ICE_ACTION_LEFTSTICK_DOWN;
	case ICE_ACTION_LEFTSTICK_UP_HASH:
		return ICE_ACTION_LEFTSTICK_UP;
	case ICE_ACTION_RIGHTSTICK_LEFT_HASH:
		return ICE_ACTION_RIGHTSTICK_LEFT;
	case ICE_ACTION_RIGHTSTICK_RIGHT_HASH:
		return ICE_ACTION_RIGHTSTICK_RIGHT;
	case ICE_ACTION_RIGHTSTICK_DOWN_HASH:
		return ICE_ACTION_RIGHTSTICK_DOWN;
	case ICE_ACTION_RIGHTSTICK_UP_HASH:
		return ICE_ACTION_RIGHTSTICK_UP;
#endif

#ifdef GAME_MW
	case ICEACTION_GRAB_LEFT_HASH:
		return ICEACTION_GRAB_LEFT;
	case ICEACTION_GRAB_RIGHT_HASH:
		return ICEACTION_GRAB_RIGHT;
	case ICEACTION_LEFT_HASH:
		return ICEACTION_LEFT;
	case ICEACTION_RIGHT_HASH:
		return ICEACTION_RIGHT;
	case ICEACTION_FAST_LEFT_HASH:
		return ICEACTION_FAST_LEFT;
	case ICEACTION_FAST_RIGHT_HASH:
		return ICEACTION_FAST_RIGHT;
	case ICEACTION_UP_HASH:
		return ICEACTION_UP;
	case ICEACTION_DOWN_HASH:
		return ICEACTION_DOWN;
	case ICEACTION_HELP_HASH:
		return ICEACTION_HELP;
	case ICEACTION_UNDO_HASH:
		return ICEACTION_UNDO;
	case ICEACTION_PLAY_HASH:
		return ICEACTION_PLAY;
	case ICEACTION_HIDE_HASH:
		return ICEACTION_HIDE;
	case ICEACTION_SCREENSHOT_HASH:
		return ICEACTION_SCREENSHOT;
	case ICEACTION_SCREENSHOT_STREAM_HASH:
		return ICEACTION_SCREENSHOT_STREAM;
	case ICEACTION_INSERT_HASH:
		return ICEACTION_INSERT;
	case ICEACTION_CUT_HASH:
		return ICEACTION_CUT;
	case ICEACTION_COPY_HASH:
		return ICEACTION_COPY;
	case ICEACTION_PASTE_HASH:
		return ICEACTION_PASTE;
	case ICEACTION_SELECT_HASH:
		return ICEACTION_SELECT;
	case ICEACTION_CANCEL_HASH:
		return ICEACTION_CANCEL;
	case ICEACTION_ALT_1_HASH:
		return ICEACTION_ALT_1;
	case ICEACTION_CLIP_IN_HASH:
		return ICEACTION_CLIP_IN;
	case ICEACTION_CLIP_OUT_HASH:
		return ICEACTION_CLIP_OUT;
	case ICEACTION_SIMSPEED_INC_HASH:
		return ICEACTION_SIMSPEED_INC;
	case ICEACTION_SIMSPEED_DEC_HASH:
		return ICEACTION_SIMSPEED_DEC;
	case ICEACTION_DUTCH_LEFT_HASH:
		return ICEACTION_DUTCH_LEFT;
	case ICEACTION_DUTCH_RIGHT_HASH:
		return ICEACTION_DUTCH_RIGHT;
	case ICEACTION_ZOOM_IN_HASH:
		return ICEACTION_ZOOM_IN;
	case ICEACTION_ZOOM_OUT_HASH:
		return ICEACTION_ZOOM_OUT;
	case ICEACTION_LETTERBOX_IN_HASH:
		return ICEACTION_LETTERBOX_IN;
	case ICEACTION_LETTERBOX_OUT_HASH:
		return ICEACTION_LETTERBOX_OUT;
	case ICEACTION_BUBBLE_IN_HASH:
		return ICEACTION_BUBBLE_IN;
	case ICEACTION_BUBBLE_OUT_HASH:
		return ICEACTION_BUBBLE_OUT;
	case ICEACTION_BUBBLE_UP_HASH:
		return ICEACTION_BUBBLE_UP;
	case ICEACTION_BUBBLE_DOWN_HASH:
		return ICEACTION_BUBBLE_DOWN;
	case ICEACTION_BUBBLE_TILT_UP_HASH:
		return ICEACTION_BUBBLE_TILT_UP;
	case ICEACTION_BUBBLE_TILT_DOWN_HASH:
		return ICEACTION_BUBBLE_TILT_DOWN;
	case ICEACTION_BUBBLE_SPIN_LEFT_HASH:
		return ICEACTION_BUBBLE_SPIN_LEFT;
	case ICEACTION_BUBBLE_SPIN_RIGHT_HASH:
		return ICEACTION_BUBBLE_SPIN_RIGHT;
	case ICEACTION_BUBBLE_LEFT_HASH:
		return ICEACTION_BUBBLE_LEFT;
	case ICEACTION_BUBBLE_RIGHT_HASH:
		return ICEACTION_BUBBLE_RIGHT;
	case ICEACTION_BUBBLE_BACK_HASH:
		return ICEACTION_BUBBLE_BACK;
	case ICEACTION_BUBBLE_FORTH_HASH:
		return ICEACTION_BUBBLE_FORTH;
	case ICEACTION_SHAKE_MAG_DEC_HASH:
		return ICEACTION_SHAKE_MAG_DEC;
	case ICEACTION_SHAKE_MAG_INC_HASH:
		return ICEACTION_SHAKE_MAG_INC;
	case ICEACTION_SHAKE_FRQ_DEC_HASH:
		return ICEACTION_SHAKE_FRQ_DEC;
	case ICEACTION_SHAKE_FRQ_INC_HASH:
		return ICEACTION_SHAKE_FRQ_INC;
	case ICEACTION_SHUTTLE_LEFT_HASH:
		return ICEACTION_SHUTTLE_LEFT;
	case ICEACTION_SHUTTLE_RIGHT_HASH:
		return ICEACTION_SHUTTLE_RIGHT;
	case ICEACTION_SHUTTLE_UP_HASH:
		return ICEACTION_SHUTTLE_UP;
	case ICEACTION_SHUTTLE_DOWN_HASH:
		return ICEACTION_SHUTTLE_DOWN;
	case ICEACTION_SHUTTLE_SPEED_DEC_HASH:
		return ICEACTION_SHUTTLE_SPEED_DEC;
	case ICEACTION_SHUTTLE_SPEED_INC_HASH:
		return ICEACTION_SHUTTLE_SPEED_INC;

#endif

	case MAX_ACTIONID_HASH:
		return MAX_ACTIONID;

	default:
		break;
	}
	return NULL_ACTION;
}

bool bIsActionAnalog(ActionID in)
{
	switch (in)
	{
	case GAMEACTION_STEERLEFT:
	case GAMEACTION_STEERRIGHT:
	case GAMEACTION_TURNLEFT:
	case GAMEACTION_TURNRIGHT:
	case GAMEACTION_GAS:
	case GAMEACTION_BRAKE:
	case FRONTENDACTION_RUP:
	case FRONTENDACTION_RDOWN:
	case FRONTENDACTION_RLEFT:
	case FRONTENDACTION_RRIGHT:
	case DEBUGACTION_MOVE_UP:
	case DEBUGACTION_MOVE_DOWN:
	case DEBUGACTION_MOVE_LEFT:
	case DEBUGACTION_MOVE_RIGHT:
	case DEBUGACTION_MOVE_FORWARD:
	case DEBUGACTION_MOVE_BACK:
	case DEBUGACTION_LOOK_UP:
	case DEBUGACTION_LOOK_DOWN:
	case DEBUGACTION_LOOK_LEFT:
	case DEBUGACTION_LOOK_RIGHT:
	case DEBUGACTION_TURBO:
	case DEBUGACTION_SUPER_TURBO:
	case FRONTENDACTION_LTRIGGER:
	case FRONTENDACTION_RTRIGGER:
		return true;
#ifdef GAME_DEBUG_VERSION
	case GAMEACTION_GAS_SLOTCAR:
		return true;
	case ICE_ACTION_LEFTSTICK_LEFT:
		return true;
	case ICE_ACTION_LEFTSTICK_RIGHT:
		return true;
	case ICE_ACTION_LEFTSTICK_DOWN:
		return true;
	case ICE_ACTION_LEFTSTICK_UP:
		return true;
	case ICE_ACTION_RIGHTSTICK_LEFT:
		return true;
	case ICE_ACTION_RIGHTSTICK_RIGHT:
		return true;
	case ICE_ACTION_RIGHTSTICK_DOWN:
		return true;
	case ICE_ACTION_RIGHTSTICK_UP:
		return true;
#endif

	default:
		break;
	}

	return false;
}

bool bIsActionFrontEnd(ActionID in)
{
	switch (in)
	{
	case FRONTENDACTION_UP:
	case FRONTENDACTION_DOWN:
	case FRONTENDACTION_LEFT:
	case FRONTENDACTION_RIGHT:
	case FRONTENDACTION_RUP:
	case FRONTENDACTION_RDOWN:
	case FRONTENDACTION_RLEFT:
	case FRONTENDACTION_RRIGHT:
	case FRONTENDACTION_ACCEPT:
	case FRONTENDACTION_CANCEL:
	case FRONTENDACTION_CANCEL_ALT:
	case FRONTENDACTION_START:
	case FRONTENDACTION_BUTTON0:
	case FRONTENDACTION_BUTTON1:
	case FRONTENDACTION_BUTTON2:
	case FRONTENDACTION_BUTTON3:
	case FRONTENDACTION_BUTTON4:
	case FRONTENDACTION_BUTTON5:
	case FRONTENDACTION_LTRIGGER:
	case FRONTENDACTION_RTRIGGER:
		return true;

	default:
		break;
	}
	return false;
}

bool bIsActionFrontEndNavigation(ActionID in)
{
	switch (in)
	{
	case FRONTENDACTION_UP:
	case FRONTENDACTION_DOWN:
	case FRONTENDACTION_LEFT:
	case FRONTENDACTION_RIGHT:
		return true;

	default:
		break;
	}
	return false;
}

bool bIsActionRelativePosition(ActionID in)
{
	switch (in)
	{
	case FRONTENDACTION_LTRIGGER:
	case FRONTENDACTION_RTRIGGER:
		return true;
	default:
		return false;
	}
	return false;
}

bool bIsActionAnalogAxis(ActionID in)
{
	switch (in)
	{
	case GAMEACTION_STEERLEFT:
	case GAMEACTION_STEERRIGHT:
	case GAMEACTION_TURNLEFT:
	case GAMEACTION_TURNRIGHT:
	case GAMEACTION_GAS:
	case GAMEACTION_BRAKE:
	case FRONTENDACTION_RUP:
	case FRONTENDACTION_RDOWN:
	case FRONTENDACTION_RLEFT:
	case FRONTENDACTION_RRIGHT:
	case FRONTENDACTION_LTRIGGER:
	case FRONTENDACTION_RTRIGGER:
	case DEBUGACTION_MOVE_UP:
	case DEBUGACTION_MOVE_DOWN:
	case DEBUGACTION_MOVE_LEFT:
	case DEBUGACTION_MOVE_RIGHT:
	case DEBUGACTION_MOVE_FORWARD:
	case DEBUGACTION_MOVE_BACK:
	case DEBUGACTION_LOOK_UP:
	case DEBUGACTION_LOOK_DOWN:
	case DEBUGACTION_LOOK_LEFT:
	case DEBUGACTION_LOOK_RIGHT:
	case DEBUGACTION_TURBO:
	case DEBUGACTION_SUPER_TURBO:
		return true;
	}
	return false;
}

bool bIsActionDigitalButton(ActionID in)
{
	switch (in)
	{
	case GAMEACTION_GAMEBREAKER:
	case CAMERAACTION_CHANGE:
	case GAMEACTION_RESET:
	case DEBUGACTION_DROPCAR:
	case CAMERAACTION_DEBUG:
	case GAMEACTION_SHIFTUP:
	case GAMEACTION_SHIFTDOWN:
	case GAMEACTION_TURNLEFT:
	case GAMEACTION_TURNRIGHT:
	case HUDACTION_PAUSEREQUEST:
	case HUDACTION_ENGAGE_EVENT:
	case HUDACTION_PAD_LEFT:
	case HUDACTION_PAD_DOWN:
	case HUDACTION_PAD_RIGHT:
	case HUDACTION_SKIPNIS:
	case HUDACTION_NEXTSONG:
		return true;
	}
	return false;
}

//bool bIsActionAnalogButton(ActionID in)
//{
//	switch (in)
//	{
//	case GAMEACTION_SHIFTUP:
//	case GAMEACTION_SHIFTDOWN:
//	//case GAMEACTION_NOS:
//		return true;
//	}
//
//	return false;
//}

bool bIsActionDebug(ActionID in)
{
	switch (in)
	{
	case DEBUGACTION_MOVE_UP:
	case DEBUGACTION_MOVE_DOWN:
	case DEBUGACTION_MOVE_LEFT:
	case DEBUGACTION_MOVE_RIGHT:
	case DEBUGACTION_MOVE_FORWARD:
	case DEBUGACTION_MOVE_BACK:
	case DEBUGACTION_MOVE_D_LEFT:
	case DEBUGACTION_MOVE_D_RIGHT:
	case DEBUGACTION_MOVE_D_FORWARD:
	case DEBUGACTION_MOVE_D_BACK:
	case DEBUGACTION_LOOK_UP:
	case DEBUGACTION_LOOK_DOWN:
	case DEBUGACTION_LOOK_LEFT:
	case DEBUGACTION_LOOK_RIGHT:
	case DEBUGACTION_LOOK_D_UP:
	case DEBUGACTION_LOOK_D_DOWN:
	case DEBUGACTION_LOOK_D_LEFT:
	case DEBUGACTION_LOOK_D_RIGHT:
	case DEBUGACTION_TURBO:
	case DEBUGACTION_SUPER_TURBO:
	case DEBUGACTION_DROPCAR:
	case DEBUGACTION_TOGGLEAI:
	case DEBUGACTION_TOGGLESIMSTEP:
	case DEBUGACTION_SIMSTEP:
	case DEBUGACTION_SCREENSHOT:
	case DEBUGACTION_STOPRECORDPATH:
	case DEBUGACTION_TOGGLECARCOLOUR:
	case DEBUGACTION_TOGGLEDEMOCAMERAS:
#ifdef GAME_DEBUG_VERSION
	case ICEACTION_GRAB_LEFT:
	case ICEACTION_GRAB_RIGHT:
	case ICEACTION_LEFT:
	case ICEACTION_RIGHT:
	case ICEACTION_FAST_LEFT:
	case ICEACTION_FAST_RIGHT:
	case ICEACTION_UP:
	case ICEACTION_DOWN:
	case ICEACTION_HELP:
	case ICEACTION_UNDO:
	case ICEACTION_PLAY:
	case ICEACTION_HIDE:
	case ICEACTION_SCREENSHOT:
	case ICEACTION_SCREENSHOT_STREAM:
	case ICEACTION_INSERT:
	case ICEACTION_CUT:
	case ICEACTION_COPY:
	case ICEACTION_PASTE:
	case ICEACTION_SELECT:
	case ICEACTION_CANCEL:
	case ICEACTION_ALT_1:
	case ICEACTION_CLIP_IN:
	case ICEACTION_CLIP_OUT:
	case ICEACTION_SIMSPEED_INC:
	case ICEACTION_SIMSPEED_DEC:
	case ICEACTION_DUTCH_LEFT:
	case ICEACTION_DUTCH_RIGHT:
	case ICEACTION_ZOOM_IN:
	case ICEACTION_ZOOM_OUT:
	case ICEACTION_LETTERBOX_IN:
	case ICEACTION_LETTERBOX_OUT:
	case ICEACTION_BUBBLE_IN:
	case ICEACTION_BUBBLE_OUT:
	case ICEACTION_BUBBLE_UP:
	case ICEACTION_BUBBLE_DOWN:
	case ICEACTION_BUBBLE_TILT_UP:
	case ICEACTION_BUBBLE_TILT_DOWN:
	case ICEACTION_BUBBLE_SPIN_LEFT:
	case ICEACTION_BUBBLE_SPIN_RIGHT:
	case ICEACTION_BUBBLE_LEFT:
	case ICEACTION_BUBBLE_RIGHT:
	case ICEACTION_BUBBLE_BACK:
	case ICEACTION_BUBBLE_FORTH:
	case ICEACTION_SHAKE_MAG_DEC:
	case ICEACTION_SHAKE_MAG_INC:
	case ICEACTION_SHAKE_FRQ_DEC:
	case ICEACTION_SHAKE_FRQ_INC:
	case ICEACTION_SHUTTLE_LEFT:
	case ICEACTION_SHUTTLE_RIGHT:
	case ICEACTION_SHUTTLE_UP:
	case ICEACTION_SHUTTLE_DOWN:
	case ICEACTION_SHUTTLE_SPEED_DEC:
	case ICEACTION_SHUTTLE_SPEED_INC:
#endif
	case CAMERAACTION_DEBUG:
	case CAMERAACTION_ENABLE_ICE:
		return true;
	}

	return false;
}

bool bIsActionTextureBindable(ActionID in)
{
	switch (in)
	{
	case FRONTENDACTION_UP:
	case FRONTENDACTION_DOWN:
	case FRONTENDACTION_LEFT:
	case FRONTENDACTION_RIGHT:
	case FRONTENDACTION_RUP:
	case FRONTENDACTION_START:
	case FRONTENDACTION_ACCEPT:
	case FRONTENDACTION_CANCEL:
	case FRONTENDACTION_BUTTON0:
	case FRONTENDACTION_BUTTON1:
	case FRONTENDACTION_BUTTON2:
	case FRONTENDACTION_BUTTON3:
	case FRONTENDACTION_BUTTON4:
	case FRONTENDACTION_BUTTON5:
	case FRONTENDACTION_LTRIGGER:
	case FRONTENDACTION_RTRIGGER:
	case GAMEACTION_SHIFTUP:
	case GAMEACTION_SHIFTDOWN:
	
		return true;
	default:
		break;
	}
	return false;
}

char* __stdcall getActionIDString(ActionID in)
{
	return ActionIDStr[in];
}
