#pragma once
#include <windows.h>
int bStringHash(char* a1);

#define VK_LBUTTON_HASH 0x1D834BE7
#define VK_RBUTTON_HASH 0xEB60B86D
#define VK_CANCEL_HASH 0x86F71565
#define VK_MBUTTON_HASH 0x6A7D88A8
#define VK_XBUTTON1_HASH 0xE102C384
#define VK_XBUTTON2_HASH 0xE102C385
#define VK_BACK_HASH 0xA59DE170
#define VK_TAB_HASH 0x81241D16
#define VK_CLEAR_HASH 0x597237A6
#define VK_RETURN_HASH 0xAA40715F
#define VK_SHIFT_HASH 0x5A919FDD
#define VK_CONTROL_HASH 0x868B8540
#define VK_MENU_HASH 0xA5A3FC14
#define VK_PAUSE_HASH 0x5A57B45D
#define VK_CAPITAL_HASH 0x66017BFD
#define VK_KANA_HASH 0xA5A2D23A
#define VK_HANGEUL_HASH 0xE6BF24C3
#define VK_HANGUL_HASH 0x92A0F39E
#define VK_IME_ON_HASH 0x95CAB836
#define VK_JUNJA_HASH 0x59F5F9F7
#define VK_FINAL_HASH 0x59A70249
#define VK_HANJA_HASH 0x59C6D161
#define VK_KANJI_HASH 0x59FD1AEC
#define VK_IME_OFF_HASH 0x4F21BE34
#define VK_ESCAPE_HASH 0x8CE11070
#define VK_CONVERT_HASH 0x868C6720
#define VK_NONCONVERT_HASH 0x5087CAAB
#define VK_ACCEPT_HASH 0x826AF6EF
#define VK_MODECHANGE_HASH 0x8F69888A
#define VK_SPACE_HASH 0x5A95E06B
#define VK_PRIOR_HASH 0x5A60D34B
#define VK_NEXT_HASH 0xA5A489BE
#define VK_END_HASH 0x8123DEF6
#define VK_HOME_HASH 0xA5A16888
#define VK_LEFT_HASH 0xA5A36EAA
#define VK_UP_HASH 0x03E9D284
#define VK_RIGHT_HASH 0x5A800B7D
#define VK_DOWN_HASH 0xA59F3857
#define VK_SELECT_HASH 0xAC90F0FF
#define VK_PRINT_HASH 0x5A60D32C
#define VK_EXECUTE_HASH 0x34D24AD2
#define VK_SNAPSHOT_HASH 0xB0843BAF
#define VK_INSERT_HASH 0x95E40FD4
#define VK_DELETE_HASH 0x899391B2
#define VK_HELP_HASH 0xA5A13DE8
#define VK_LWIN_HASH 0xA5A3BB99
#define VK_RWIN_HASH 0xA5A705DF
#define VK_APPS_HASH 0xA59D9693
#define VK_SLEEP_HASH 0x5A93C038
#define VK_NUMPAD0_HASH 0xE3368174
#define VK_NUMPAD1_HASH 0xE3368175
#define VK_NUMPAD2_HASH 0xE3368176
#define VK_NUMPAD3_HASH 0xE3368177
#define VK_NUMPAD4_HASH 0xE3368178
#define VK_NUMPAD5_HASH 0xE3368179
#define VK_NUMPAD6_HASH 0xE336817A
#define VK_NUMPAD7_HASH 0xE336817B
#define VK_NUMPAD8_HASH 0xE336817C
#define VK_NUMPAD9_HASH 0xE336817D
#define VK_MULTIPLY_HASH 0x5BBCAE7F
#define VK_ADD_HASH 0x8123CCA8
#define VK_SEPARATOR_HASH 0xD2518950
#define VK_SUBTRACT_HASH 0xCDF8C3E7
#define VK_DECIMAL_HASH 0xBB64FEEE
#define VK_DIVIDE_HASH 0x89E17E74
#define VK_F1_HASH 0x03E9D076
#define VK_F2_HASH 0x03E9D077
#define VK_F3_HASH 0x03E9D078
#define VK_F4_HASH 0x03E9D079
#define VK_F5_HASH 0x03E9D07A
#define VK_F6_HASH 0x03E9D07B
#define VK_F7_HASH 0x03E9D07C
#define VK_F8_HASH 0x03E9D07D
#define VK_F9_HASH 0x03E9D07E
#define VK_F10_HASH 0x8123DF66
#define VK_F11_HASH 0x8123DF67
#define VK_F12_HASH 0x8123DF68
#define VK_F13_HASH 0x8123DF69
#define VK_F14_HASH 0x8123DF6A
#define VK_F15_HASH 0x8123DF6B
#define VK_F16_HASH 0x8123DF6C
#define VK_F17_HASH 0x8123DF6D
#define VK_F18_HASH 0x8123DF6E
#define VK_F19_HASH 0x8123DF6F
#define VK_F20_HASH 0x8123DF87
#define VK_F21_HASH 0x8123DF88
#define VK_F22_HASH 0x8123DF89
#define VK_F23_HASH 0x8123DF8A
#define VK_F24_HASH 0x8123DF8B
#define VK_NAVIGATION_VIEW_HASH 0x5B9AC209
#define VK_NAVIGATION_MENU_HASH 0x5B95C2C3
#define VK_NAVIGATION_UP_HASH 0x280C2173
#define VK_NAVIGATION_DOWN_HASH 0x5B90FF06
#define VK_NAVIGATION_LEFT_HASH 0x5B953559
#define VK_NAVIGATION_RIGHT_HASH 0xCEAAA80C
#define VK_NAVIGATION_ACCEPT_HASH 0x7BE9255E
#define VK_NAVIGATION_CANCEL_HASH 0x807543D4
#define VK_NUMLOCK_HASH 0xE3348B78
#define VK_SCROLL_HASH 0xAC7035EE
#define VK_OEM_NEC_EQUAL_HASH 0xDA4D1C8C
#define VK_OEM_FJ_JISHO_HASH 0xD9A5C46B
#define VK_OEM_FJ_MASSHOU_HASH 0xAE73F14E
#define VK_OEM_FJ_TOUROKU_HASH 0xEA179547
#define VK_OEM_FJ_LOYA_HASH 0x63B0E3A3
#define VK_OEM_FJ_ROYA_HASH 0x63B42DE9
#define VK_LSHIFT_HASH 0x9D380B89
#define VK_RSHIFT_HASH 0xAB36FF4F
#define VK_LCONTROL_HASH 0x0C7B8BEC
#define VK_RCONTROL_HASH 0x96068932
#define VK_LMENU_HASH 0x5A15A240
#define VK_RMENU_HASH 0x5A823546
#define VK_BROWSER_BACK_HASH 0xE8CA4333
#define VK_BROWSER_FORWARD_HASH 0x270BA997
#define VK_BROWSER_REFRESH_HASH 0xAA971991
#define VK_BROWSER_STOP_HASH 0xE8D3E808
#define VK_BROWSER_SEARCH_HASH 0x6C56FE98
#define VK_BROWSER_FAVORITES_HASH 0x4F717375
#define VK_BROWSER_HOME_HASH 0xE8CDCA4B
#define VK_VOLUME_MUTE_HASH 0x91C34551
#define VK_VOLUME_DOWN_HASH 0x91BE3CCE
#define VK_VOLUME_UP_HASH 0x64BF4D3B
#define VK_MEDIA_NEXT_TRACK_HASH 0xD25DFD11
#define VK_MEDIA_PREV_TRACK_HASH 0xD5D6892F
#define VK_MEDIA_STOP_HASH 0x3375ED44
#define VK_MEDIA_PLAY_PAUSE_HASH 0x5081E891
#define VK_LAUNCH_MAIL_HASH 0xCB5C2BBC
#define VK_LAUNCH_MEDIA_SELECT_HASH 0xD1BE0F18
#define VK_LAUNCH_APP1_HASH 0xCB55D7CB
#define VK_LAUNCH_APP2_HASH 0xCB55D7CC
#define VK_OEM_1_HASH 0x5A47ACD0
#define VK_OEM_PLUS_HASH 0x67BC8923
#define VK_OEM_COMMA_HASH 0x5E63F18C
#define VK_OEM_MINUS_HASH 0x5F15A1AB
#define VK_OEM_PERIOD_HASH 0x4882ED22
#define VK_OEM_2_HASH 0x5A47ACD1
#define VK_OEM_3_HASH 0x5A47ACD2
#define VK_GAMEPAD_A_HASH 0xCDB662EE
#define VK_GAMEPAD_B_HASH 0xCDB662EF
#define VK_GAMEPAD_X_HASH 0xCDB66305
#define VK_GAMEPAD_Y_HASH 0xCDB66306
#define VK_GAMEPAD_RIGHT_SHOULDER_HASH 0xC3FDCC90
#define VK_GAMEPAD_LEFT_SHOULDER_HASH 0xD88E889D
#define VK_GAMEPAD_LEFT_TRIGGER_HASH 0xCF42A88B
#define VK_GAMEPAD_RIGHT_TRIGGER_HASH 0x810FBA1E
#define VK_GAMEPAD_DPAD_UP_HASH 0xC066E7EA
#define VK_GAMEPAD_DPAD_DOWN_HASH 0x75B73F3D
#define VK_GAMEPAD_DPAD_LEFT_HASH 0x75BB7590
#define VK_GAMEPAD_DPAD_RIGHT_HASH 0x2D98EF23
#define VK_GAMEPAD_MENU_HASH 0xB03D68A2
#define VK_GAMEPAD_VIEW_HASH 0xB04267E8
#define VK_GAMEPAD_LEFT_THUMBSTICK_BUTTON_HASH 0x51E067D0
#define VK_GAMEPAD_RIGHT_THUMBSTICK_BUTTON_HASH 0x2432CD23
#define VK_GAMEPAD_LEFT_THUMBSTICK_UP_HASH 0x19E58D19
#define VK_GAMEPAD_LEFT_THUMBSTICK_DOWN_HASH 0x2973EC2C
#define VK_GAMEPAD_LEFT_THUMBSTICK_RIGHT_HASH 0x58EB39F2
#define VK_GAMEPAD_LEFT_THUMBSTICK_LEFT_HASH 0x2978227F
#define VK_GAMEPAD_RIGHT_THUMBSTICK_UP_HASH 0x032C40EC
#define VK_GAMEPAD_RIGHT_THUMBSTICK_DOWN_HASH 0x7F36E0BF
#define VK_GAMEPAD_RIGHT_THUMBSTICK_RIGHT_HASH 0x670CC0E5
#define VK_GAMEPAD_RIGHT_THUMBSTICK_LEFT_HASH 0x7F3B1712
#define VK_OEM_4_HASH 0x5A47ACD3
#define VK_OEM_5_HASH 0x5A47ACD4
#define VK_OEM_6_HASH 0x5A47ACD5
#define VK_OEM_7_HASH 0x5A47ACD6
#define VK_OEM_8_HASH 0x5A47ACD7
#define VK_OEM_AX_HASH 0xA33D4938
#define VK_OEM_102_HASH 0x0AE62732
#define VK_ICO_HELP_HASH 0x48E2E1A2
#define VK_ICO_00_HASH 0x951B3AD9
#define VK_PROCESSKEY_HASH 0x8B596BC7
#define VK_ICO_CLEAR_HASH 0x64E852A0
#define VK_PACKET_HASH 0xA5443F77
#define VK_OEM_RESET_HASH 0x5F6DFDE2
#define VK_OEM_JUMP_HASH 0x67B9641B
#define VK_OEM_PA1_HASH 0x0AE6AD41
#define VK_OEM_PA2_HASH 0x0AE6AD42
#define VK_OEM_PA3_HASH 0x0AE6AD43
#define VK_OEM_WSCTRL_HASH 0x59CC561E
#define VK_OEM_CUSEL_HASH 0x5E67545B
#define VK_OEM_ATTN_HASH 0x67B47156
#define VK_OEM_FINISH_HASH 0x317587E0
#define VK_OEM_COPY_HASH 0x67B5745A
#define VK_OEM_AUTO_HASH 0x67B47598
#define VK_OEM_ENLW_HASH 0x67B68855
#define VK_OEM_BACKTAB_HASH 0x18CE5AA7
#define VK_ATTN_HASH 0xA59DA816
#define VK_CRSEL_HASH 0x5975BDF8
#define VK_EXSEL_HASH 0x599D3940
#define VK_EREOF_HASH 0x5999B4B0
#define VK_PLAY_HASH 0xA5A5BD55
#define VK_ZOOM_HASH 0xA5AB47A4
#define VK_NONAME_HASH 0xA19D23DD
#define VK_PA1_HASH 0x81240C01
#define VK_OEM_CLEAR_HASH 0x5E6228E6

unsigned char ConvertVKNameToValue(char* name)
{
	for (int i = 0; i<strlen(name); ++i)
		name[i] = toupper(name[i]);

	switch (bStringHash(name))
	{
	case VK_LBUTTON_HASH:
		return VK_LBUTTON;
	case VK_RBUTTON_HASH:
		return VK_RBUTTON;
	case VK_CANCEL_HASH:
		return VK_CANCEL;
	case VK_MBUTTON_HASH:
		return VK_MBUTTON;
	case VK_XBUTTON1_HASH:
		return VK_XBUTTON1;
	case VK_XBUTTON2_HASH:
		return VK_XBUTTON2;
	case VK_BACK_HASH:
		return VK_BACK;
	case VK_TAB_HASH:
		return VK_TAB;
	case VK_CLEAR_HASH:
		return VK_CLEAR;
	case VK_RETURN_HASH:
		return VK_RETURN;
	case VK_SHIFT_HASH:
		return VK_SHIFT;
	case VK_CONTROL_HASH:
		return VK_CONTROL;
	case VK_MENU_HASH:
		return VK_MENU;
	case VK_PAUSE_HASH:
		return VK_PAUSE;
	case VK_CAPITAL_HASH:
		return VK_CAPITAL;
	case VK_KANA_HASH:
		return VK_KANA;
	case VK_HANGEUL_HASH:
		return VK_HANGEUL;
	case VK_HANGUL_HASH:
		return VK_HANGUL;
	case VK_IME_ON_HASH:
		return VK_IME_ON;
	case VK_JUNJA_HASH:
		return VK_JUNJA;
	case VK_FINAL_HASH:
		return VK_FINAL;
	case VK_HANJA_HASH:
		return VK_HANJA;
	case VK_KANJI_HASH:
		return VK_KANJI;
	case VK_IME_OFF_HASH:
		return VK_IME_OFF;
	case VK_ESCAPE_HASH:
		return VK_ESCAPE;
	case VK_CONVERT_HASH:
		return VK_CONVERT;
	case VK_NONCONVERT_HASH:
		return VK_NONCONVERT;
	case VK_ACCEPT_HASH:
		return VK_ACCEPT;
	case VK_MODECHANGE_HASH:
		return VK_MODECHANGE;
	case VK_SPACE_HASH:
		return VK_SPACE;
	case VK_PRIOR_HASH:
		return VK_PRIOR;
	case VK_NEXT_HASH:
		return VK_NEXT;
	case VK_END_HASH:
		return VK_END;
	case VK_HOME_HASH:
		return VK_HOME;
	case VK_LEFT_HASH:
		return VK_LEFT;
	case VK_UP_HASH:
		return VK_UP;
	case VK_RIGHT_HASH:
		return VK_RIGHT;
	case VK_DOWN_HASH:
		return VK_DOWN;
	case VK_SELECT_HASH:
		return VK_SELECT;
	case VK_PRINT_HASH:
		return VK_PRINT;
	case VK_EXECUTE_HASH:
		return VK_EXECUTE;
	case VK_SNAPSHOT_HASH:
		return VK_SNAPSHOT;
	case VK_INSERT_HASH:
		return VK_INSERT;
	case VK_DELETE_HASH:
		return VK_DELETE;
	case VK_HELP_HASH:
		return VK_HELP;
	case VK_LWIN_HASH:
		return VK_LWIN;
	case VK_RWIN_HASH:
		return VK_RWIN;
	case VK_APPS_HASH:
		return VK_APPS;
	case VK_SLEEP_HASH:
		return VK_SLEEP;
	case VK_NUMPAD0_HASH:
		return VK_NUMPAD0;
	case VK_NUMPAD1_HASH:
		return VK_NUMPAD1;
	case VK_NUMPAD2_HASH:
		return VK_NUMPAD2;
	case VK_NUMPAD3_HASH:
		return VK_NUMPAD3;
	case VK_NUMPAD4_HASH:
		return VK_NUMPAD4;
	case VK_NUMPAD5_HASH:
		return VK_NUMPAD5;
	case VK_NUMPAD6_HASH:
		return VK_NUMPAD6;
	case VK_NUMPAD7_HASH:
		return VK_NUMPAD7;
	case VK_NUMPAD8_HASH:
		return VK_NUMPAD8;
	case VK_NUMPAD9_HASH:
		return VK_NUMPAD9;
	case VK_MULTIPLY_HASH:
		return VK_MULTIPLY;
	case VK_ADD_HASH:
		return VK_ADD;
	case VK_SEPARATOR_HASH:
		return VK_SEPARATOR;
	case VK_SUBTRACT_HASH:
		return VK_SUBTRACT;
	case VK_DECIMAL_HASH:
		return VK_DECIMAL;
	case VK_DIVIDE_HASH:
		return VK_DIVIDE;
	case VK_F1_HASH:
		return VK_F1;
	case VK_F2_HASH:
		return VK_F2;
	case VK_F3_HASH:
		return VK_F3;
	case VK_F4_HASH:
		return VK_F4;
	case VK_F5_HASH:
		return VK_F5;
	case VK_F6_HASH:
		return VK_F6;
	case VK_F7_HASH:
		return VK_F7;
	case VK_F8_HASH:
		return VK_F8;
	case VK_F9_HASH:
		return VK_F9;
	case VK_F10_HASH:
		return VK_F10;
	case VK_F11_HASH:
		return VK_F11;
	case VK_F12_HASH:
		return VK_F12;
	case VK_F13_HASH:
		return VK_F13;
	case VK_F14_HASH:
		return VK_F14;
	case VK_F15_HASH:
		return VK_F15;
	case VK_F16_HASH:
		return VK_F16;
	case VK_F17_HASH:
		return VK_F17;
	case VK_F18_HASH:
		return VK_F18;
	case VK_F19_HASH:
		return VK_F19;
	case VK_F20_HASH:
		return VK_F20;
	case VK_F21_HASH:
		return VK_F21;
	case VK_F22_HASH:
		return VK_F22;
	case VK_F23_HASH:
		return VK_F23;
	case VK_F24_HASH:
		return VK_F24;
	case VK_NAVIGATION_VIEW_HASH:
		return VK_NAVIGATION_VIEW;
	case VK_NAVIGATION_MENU_HASH:
		return VK_NAVIGATION_MENU;
	case VK_NAVIGATION_UP_HASH:
		return VK_NAVIGATION_UP;
	case VK_NAVIGATION_DOWN_HASH:
		return VK_NAVIGATION_DOWN;
	case VK_NAVIGATION_LEFT_HASH:
		return VK_NAVIGATION_LEFT;
	case VK_NAVIGATION_RIGHT_HASH:
		return VK_NAVIGATION_RIGHT;
	case VK_NAVIGATION_ACCEPT_HASH:
		return VK_NAVIGATION_ACCEPT;
	case VK_NAVIGATION_CANCEL_HASH:
		return VK_NAVIGATION_CANCEL;
	case VK_NUMLOCK_HASH:
		return VK_NUMLOCK;
	case VK_SCROLL_HASH:
		return VK_SCROLL;
	case VK_OEM_NEC_EQUAL_HASH:
		return VK_OEM_NEC_EQUAL;
	case VK_OEM_FJ_JISHO_HASH:
		return VK_OEM_FJ_JISHO;
	case VK_OEM_FJ_MASSHOU_HASH:
		return VK_OEM_FJ_MASSHOU;
	case VK_OEM_FJ_TOUROKU_HASH:
		return VK_OEM_FJ_TOUROKU;
	case VK_OEM_FJ_LOYA_HASH:
		return VK_OEM_FJ_LOYA;
	case VK_OEM_FJ_ROYA_HASH:
		return VK_OEM_FJ_ROYA;
	case VK_LSHIFT_HASH:
		return VK_LSHIFT;
	case VK_RSHIFT_HASH:
		return VK_RSHIFT;
	case VK_LCONTROL_HASH:
		return VK_LCONTROL;
	case VK_RCONTROL_HASH:
		return VK_RCONTROL;
	case VK_LMENU_HASH:
		return VK_LMENU;
	case VK_RMENU_HASH:
		return VK_RMENU;
	case VK_BROWSER_BACK_HASH:
		return VK_BROWSER_BACK;
	case VK_BROWSER_FORWARD_HASH:
		return VK_BROWSER_FORWARD;
	case VK_BROWSER_REFRESH_HASH:
		return VK_BROWSER_REFRESH;
	case VK_BROWSER_STOP_HASH:
		return VK_BROWSER_STOP;
	case VK_BROWSER_SEARCH_HASH:
		return VK_BROWSER_SEARCH;
	case VK_BROWSER_FAVORITES_HASH:
		return VK_BROWSER_FAVORITES;
	case VK_BROWSER_HOME_HASH:
		return VK_BROWSER_HOME;
	case VK_VOLUME_MUTE_HASH:
		return VK_VOLUME_MUTE;
	case VK_VOLUME_DOWN_HASH:
		return VK_VOLUME_DOWN;
	case VK_VOLUME_UP_HASH:
		return VK_VOLUME_UP;
	case VK_MEDIA_NEXT_TRACK_HASH:
		return VK_MEDIA_NEXT_TRACK;
	case VK_MEDIA_PREV_TRACK_HASH:
		return VK_MEDIA_PREV_TRACK;
	case VK_MEDIA_STOP_HASH:
		return VK_MEDIA_STOP;
	case VK_MEDIA_PLAY_PAUSE_HASH:
		return VK_MEDIA_PLAY_PAUSE;
	case VK_LAUNCH_MAIL_HASH:
		return VK_LAUNCH_MAIL;
	case VK_LAUNCH_MEDIA_SELECT_HASH:
		return VK_LAUNCH_MEDIA_SELECT;
	case VK_LAUNCH_APP1_HASH:
		return VK_LAUNCH_APP1;
	case VK_LAUNCH_APP2_HASH:
		return VK_LAUNCH_APP2;
	case VK_OEM_1_HASH:
		return VK_OEM_1;
	case VK_OEM_PLUS_HASH:
		return VK_OEM_PLUS;
	case VK_OEM_COMMA_HASH:
		return VK_OEM_COMMA;
	case VK_OEM_MINUS_HASH:
		return VK_OEM_MINUS;
	case VK_OEM_PERIOD_HASH:
		return VK_OEM_PERIOD;
	case VK_OEM_2_HASH:
		return VK_OEM_2;
	case VK_OEM_3_HASH:
		return VK_OEM_3;
	case VK_GAMEPAD_A_HASH:
		return VK_GAMEPAD_A;
	case VK_GAMEPAD_B_HASH:
		return VK_GAMEPAD_B;
	case VK_GAMEPAD_X_HASH:
		return VK_GAMEPAD_X;
	case VK_GAMEPAD_Y_HASH:
		return VK_GAMEPAD_Y;
	case VK_GAMEPAD_RIGHT_SHOULDER_HASH:
		return VK_GAMEPAD_RIGHT_SHOULDER;
	case VK_GAMEPAD_LEFT_SHOULDER_HASH:
		return VK_GAMEPAD_LEFT_SHOULDER;
	case VK_GAMEPAD_LEFT_TRIGGER_HASH:
		return VK_GAMEPAD_LEFT_TRIGGER;
	case VK_GAMEPAD_RIGHT_TRIGGER_HASH:
		return VK_GAMEPAD_RIGHT_TRIGGER;
	case VK_GAMEPAD_DPAD_UP_HASH:
		return VK_GAMEPAD_DPAD_UP;
	case VK_GAMEPAD_DPAD_DOWN_HASH:
		return VK_GAMEPAD_DPAD_DOWN;
	case VK_GAMEPAD_DPAD_LEFT_HASH:
		return VK_GAMEPAD_DPAD_LEFT;
	case VK_GAMEPAD_DPAD_RIGHT_HASH:
		return VK_GAMEPAD_DPAD_RIGHT;
	case VK_GAMEPAD_MENU_HASH:
		return VK_GAMEPAD_MENU;
	case VK_GAMEPAD_VIEW_HASH:
		return VK_GAMEPAD_VIEW;
	case VK_GAMEPAD_LEFT_THUMBSTICK_BUTTON_HASH:
		return VK_GAMEPAD_LEFT_THUMBSTICK_BUTTON;
	case VK_GAMEPAD_RIGHT_THUMBSTICK_BUTTON_HASH:
		return VK_GAMEPAD_RIGHT_THUMBSTICK_BUTTON;
	case VK_GAMEPAD_LEFT_THUMBSTICK_UP_HASH:
		return VK_GAMEPAD_LEFT_THUMBSTICK_UP;
	case VK_GAMEPAD_LEFT_THUMBSTICK_DOWN_HASH:
		return VK_GAMEPAD_LEFT_THUMBSTICK_DOWN;
	case VK_GAMEPAD_LEFT_THUMBSTICK_RIGHT_HASH:
		return VK_GAMEPAD_LEFT_THUMBSTICK_RIGHT;
	case VK_GAMEPAD_LEFT_THUMBSTICK_LEFT_HASH:
		return VK_GAMEPAD_LEFT_THUMBSTICK_LEFT;
	case VK_GAMEPAD_RIGHT_THUMBSTICK_UP_HASH:
		return VK_GAMEPAD_RIGHT_THUMBSTICK_UP;
	case VK_GAMEPAD_RIGHT_THUMBSTICK_DOWN_HASH:
		return VK_GAMEPAD_RIGHT_THUMBSTICK_DOWN;
	case VK_GAMEPAD_RIGHT_THUMBSTICK_RIGHT_HASH:
		return VK_GAMEPAD_RIGHT_THUMBSTICK_RIGHT;
	case VK_GAMEPAD_RIGHT_THUMBSTICK_LEFT_HASH:
		return VK_GAMEPAD_RIGHT_THUMBSTICK_LEFT;
	case VK_OEM_4_HASH:
		return VK_OEM_4;
	case VK_OEM_5_HASH:
		return VK_OEM_5;
	case VK_OEM_6_HASH:
		return VK_OEM_6;
	case VK_OEM_7_HASH:
		return VK_OEM_7;
	case VK_OEM_8_HASH:
		return VK_OEM_8;
	case VK_OEM_AX_HASH:
		return VK_OEM_AX;
	case VK_OEM_102_HASH:
		return VK_OEM_102;
	case VK_ICO_HELP_HASH:
		return VK_ICO_HELP;
	case VK_ICO_00_HASH:
		return VK_ICO_00;
	case VK_PROCESSKEY_HASH:
		return VK_PROCESSKEY;
	case VK_ICO_CLEAR_HASH:
		return VK_ICO_CLEAR;
	case VK_PACKET_HASH:
		return VK_PACKET;
	case VK_OEM_RESET_HASH:
		return VK_OEM_RESET;
	case VK_OEM_JUMP_HASH:
		return VK_OEM_JUMP;
	case VK_OEM_PA1_HASH:
		return VK_OEM_PA1;
	case VK_OEM_PA2_HASH:
		return VK_OEM_PA2;
	case VK_OEM_PA3_HASH:
		return VK_OEM_PA3;
	case VK_OEM_WSCTRL_HASH:
		return VK_OEM_WSCTRL;
	case VK_OEM_CUSEL_HASH:
		return VK_OEM_CUSEL;
	case VK_OEM_ATTN_HASH:
		return VK_OEM_ATTN;
	case VK_OEM_FINISH_HASH:
		return VK_OEM_FINISH;
	case VK_OEM_COPY_HASH:
		return VK_OEM_COPY;
	case VK_OEM_AUTO_HASH:
		return VK_OEM_AUTO;
	case VK_OEM_ENLW_HASH:
		return VK_OEM_ENLW;
	case VK_OEM_BACKTAB_HASH:
		return VK_OEM_BACKTAB;
	case VK_ATTN_HASH:
		return VK_ATTN;
	case VK_CRSEL_HASH:
		return VK_CRSEL;
	case VK_EXSEL_HASH:
		return VK_EXSEL;
	case VK_EREOF_HASH:
		return VK_EREOF;
	case VK_PLAY_HASH:
		return VK_PLAY;
	case VK_ZOOM_HASH:
		return VK_ZOOM;
	case VK_NONAME_HASH:
		return VK_NONAME;
	case VK_PA1_HASH:
		return VK_PA1;
	case VK_OEM_CLEAR_HASH:
		return VK_OEM_CLEAR;

	default:
		break;
	}
	return 0;
}
