/*
// clang-format off
// 
//    MIT License
//    Need for Speed (Black Box, MW & newer) - Xtended Input plugin
//    Bringing native XInput to NFS
//    
//    Copyright (c) 2022–2023 Lovro Plese (Xan/Tenjoin)
//    Copyright (c) 2023 Berkay Yigit <mail@berkay.link>
//
// clang-format on
*/

#pragma once
#include "NFS_XtendedInput.h"
#include "NFS_XtendedInput_XInputConfig.h"

#define XBONE_A_HASH             NFS_HASH("XBONE_A")
#define XBONE_B_HASH             NFS_HASH("XBONE_B")
#define XBONE_DPAD_HASH          NFS_HASH("XBONE_DPAD")
#define XBONE_DPAD_DOWN_HASH     NFS_HASH("XBONE_DPAD_DOWN")
#define XBONE_DPAD_LEFT_HASH     NFS_HASH("XBONE_DPAD_LEFT")
#define XBONE_DPAD_RIGHT_HASH    NFS_HASH("XBONE_DPAD_RIGHT")
#define XBONE_DPAD_UP_HASH       NFS_HASH("XBONE_DPAD_UP")
#define XBONE_DPAD_X_HASH        NFS_HASH("XBONE_DPAD_X")
#define XBONE_DPAD_Y_HASH        NFS_HASH("XBONE_DPAD_Y")
#define XBONE_LANALOG_HASH       NFS_HASH("XBONE_LANALOG")
#define XBONE_LANALOG_DOWN_HASH  NFS_HASH("XBONE_LANALOG_DOWN")
#define XBONE_LANALOG_LEFT_HASH  NFS_HASH("XBONE_LANALOG_LEFT")
#define XBONE_LANALOG_RIGHT_HASH NFS_HASH("XBONE_LANALOG_RIGHT")
#define XBONE_LANALOG_UP_HASH    NFS_HASH("XBONE_LANALOG_UP")
#define XBONE_LANALOG_X_HASH     NFS_HASH("XBONE_LANALOG_X")
#define XBONE_LANALOG_Y_HASH     NFS_HASH("XBONE_LANALOG_Y")
#define XBONE_LB_HASH            NFS_HASH("XBONE_LB")
#define XBONE_LS_HASH            NFS_HASH("XBONE_LS")
#define XBONE_LT_HASH            NFS_HASH("XBONE_LT")
#define XBONE_MENU_HASH          NFS_HASH("XBONE_MENU")
#define XBONE_RANALOG_HASH       NFS_HASH("XBONE_RANALOG")
#define XBONE_RANALOG_DOWN_HASH  NFS_HASH("XBONE_RANALOG_DOWN")
#define XBONE_RANALOG_LEFT_HASH  NFS_HASH("XBONE_RANALOG_LEFT")
#define XBONE_RANALOG_RIGHT_HASH NFS_HASH("XBONE_RANALOG_RIGHT")
#define XBONE_RANALOG_UP_HASH    NFS_HASH("XBONE_RANALOG_UP")
#define XBONE_RANALOG_X_HASH     NFS_HASH("XBONE_RANALOG_X")
#define XBONE_RANALOG_Y_HASH     NFS_HASH("XBONE_RANALOG_Y")
#define XBONE_RB_HASH            NFS_HASH("XBONE_RB")
#define XBONE_RS_HASH            NFS_HASH("XBONE_RS")
#define XBONE_RT_HASH            NFS_HASH("XBONE_RT")
#define XBONE_VIEW_HASH          NFS_HASH("XBONE_VIEW")
#define XBONE_X_HASH             NFS_HASH("XBONE_X")
#define XBONE_Y_HASH             NFS_HASH("XBONE_Y")

#define PS4_CIRCLE_HASH        NFS_HASH("PS4_CIRCLE")
#define PS4_CROSS_HASH         NFS_HASH("PS4_CROSS")
#define PS4_DPAD_HASH          NFS_HASH("PS4_DPAD")
#define PS4_DPAD_DOWN_HASH     NFS_HASH("PS4_DPAD_DOWN")
#define PS4_DPAD_LEFT_HASH     NFS_HASH("PS4_DPAD_LEFT")
#define PS4_DPAD_RIGHT_HASH    NFS_HASH("PS4_DPAD_RIGHT")
#define PS4_DPAD_UP_HASH       NFS_HASH("PS4_DPAD_UP")
#define PS4_DPAD_X_HASH        NFS_HASH("PS4_DPAD_X")
#define PS4_DPAD_Y_HASH        NFS_HASH("PS4_DPAD_Y")
#define PS4_L1_HASH            NFS_HASH("PS4_L1")
#define PS4_L2_HASH            NFS_HASH("PS4_L2")
#define PS4_L3_HASH            NFS_HASH("PS4_L3")
#define PS4_LANALOG_HASH       NFS_HASH("PS4_LANALOG")
#define PS4_LANALOG_DOWN_HASH  NFS_HASH("PS4_LANALOG_DOWN")
#define PS4_LANALOG_LEFT_HASH  NFS_HASH("PS4_LANALOG_LEFT")
#define PS4_LANALOG_RIGHT_HASH NFS_HASH("PS4_LANALOG_RIGHT")
#define PS4_LANALOG_UP_HASH    NFS_HASH("PS4_LANALOG_UP")
#define PS4_LANALOG_X_HASH     NFS_HASH("PS4_LANALOG_X")
#define PS4_LANALOG_Y_HASH     NFS_HASH("PS4_LANALOG_Y")
#define PS4_R1_HASH            NFS_HASH("PS4_R1")
#define PS4_R2_HASH            NFS_HASH("PS4_R2")
#define PS4_R3_HASH            NFS_HASH("PS4_R3")
#define PS4_RANALOG_HASH       NFS_HASH("PS4_RANALOG")
#define PS4_RANALOG_DOWN_HASH  NFS_HASH("PS4_RANALOG_DOWN")
#define PS4_RANALOG_LEFT_HASH  NFS_HASH("PS4_RANALOG_LEFT")
#define PS4_RANALOG_RIGHT_HASH NFS_HASH("PS4_RANALOG_RIGHT")
#define PS4_RANALOG_UP_HASH    NFS_HASH("PS4_RANALOG_UP")
#define PS4_RANALOG_X_HASH     NFS_HASH("PS4_RANALOG_X")
#define PS4_RANALOG_Y_HASH     NFS_HASH("PS4_RANALOG_Y")
#define PS4_SHARE_HASH         NFS_HASH("PS4_SHARE")
#define PS4_SQUARE_HASH        NFS_HASH("PS4_SQUARE")
#define PS4_START_HASH         NFS_HASH("PS4_START")
#define PS4_TRIANGLE_HASH      NFS_HASH("PS4_TRIANGLE")

#define XB360_A_HASH             NFS_HASH("XB360_A")
#define XB360_B_HASH             NFS_HASH("XB360_B")
#define XB360_BACK_HASH          NFS_HASH("XB360_BACK")
#define XB360_DPAD_HASH          NFS_HASH("XB360_DPAD")
#define XB360_DPAD_DOWN_HASH     NFS_HASH("XB360_DPAD_DOWN")
#define XB360_DPAD_LEFT_HASH     NFS_HASH("XB360_DPAD_LEFT")
#define XB360_DPAD_RIGHT_HASH    NFS_HASH("XB360_DPAD_RIGHT")
#define XB360_DPAD_UP_HASH       NFS_HASH("XB360_DPAD_UP")
#define XB360_DPAD_X_HASH        NFS_HASH("XB360_DPAD_X")
#define XB360_DPAD_Y_HASH        NFS_HASH("XB360_DPAD_Y")
#define XB360_LANALOG_HASH       NFS_HASH("XB360_LANALOG")
#define XB360_LANALOG_DOWN_HASH  NFS_HASH("XB360_LANALOG_DOWN")
#define XB360_LANALOG_LEFT_HASH  NFS_HASH("XB360_LANALOG_LEFT")
#define XB360_LANALOG_RIGHT_HASH NFS_HASH("XB360_LANALOG_RIGHT")
#define XB360_LANALOG_UP_HASH    NFS_HASH("XB360_LANALOG_UP")
#define XB360_LB_HASH            NFS_HASH("XB360_LB")
#define XB360_LS_HASH            NFS_HASH("XB360_LS")
#define XB360_LT_HASH            NFS_HASH("XB360_LT")
#define XB360_RANALOG_HASH       NFS_HASH("XB360_RANALOG")
#define XB360_RANALOG_DOWN_HASH  NFS_HASH("XB360_RANALOG_DOWN")
#define XB360_RANALOG_LEFT_HASH  NFS_HASH("XB360_RANALOG_LEFT")
#define XB360_RANALOG_RIGHT_HASH NFS_HASH("XB360_RANALOG_RIGHT")
#define XB360_RANALOG_UP_HASH    NFS_HASH("XB360_RANALOG_UP")
#define XB360_RB_HASH            NFS_HASH("XB360_RB")
#define XB360_RS_HASH            NFS_HASH("XB360_RS")
#define XB360_RT_HASH            NFS_HASH("XB360_RT")
#define XB360_START_HASH         NFS_HASH("XB360_START")
#define XB360_X_HASH             NFS_HASH("XB360_X")
#define XB360_Y_HASH             NFS_HASH("XB360_Y")

#define PS3_CIRCLE_HASH        NFS_HASH("PS3_CIRCLE")
#define PS3_CROSS_HASH         NFS_HASH("PS3_CROSS")
#define PS3_DPAD_HASH          NFS_HASH("PS3_DPAD")
#define PS3_DPAD_DOWN_HASH     NFS_HASH("PS3_DPAD_DOWN")
#define PS3_DPAD_LEFT_HASH     NFS_HASH("PS3_DPAD_LEFT")
#define PS3_DPAD_RIGHT_HASH    NFS_HASH("PS3_DPAD_RIGHT")
#define PS3_DPAD_UP_HASH       NFS_HASH("PS3_DPAD_UP")
#define PS3_DPAD_X_HASH        NFS_HASH("PS3_DPAD_X")
#define PS3_DPAD_Y_HASH        NFS_HASH("PS3_DPAD_Y")
#define PS3_L1_HASH            NFS_HASH("PS3_L1")
#define PS3_L2_HASH            NFS_HASH("PS3_L2")
#define PS3_L3_HASH            NFS_HASH("PS3_L3")
#define PS3_LANALOG_HASH       NFS_HASH("PS3_LANALOG")
#define PS3_LANALOG_DOWN_HASH  NFS_HASH("PS3_LANALOG_DOWN")
#define PS3_LANALOG_LEFT_HASH  NFS_HASH("PS3_LANALOG_LEFT")
#define PS3_LANALOG_RIGHT_HASH NFS_HASH("PS3_LANALOG_RIGHT")
#define PS3_LANALOG_UP_HASH    NFS_HASH("PS3_LANALOG_UP")
#define PS3_R1_HASH            NFS_HASH("PS3_R1")
#define PS3_R2_HASH            NFS_HASH("PS3_R2")
#define PS3_R3_HASH            NFS_HASH("PS3_R3")
#define PS3_RANALOG_HASH       NFS_HASH("PS3_RANALOG")
#define PS3_RANALOG_DOWN_HASH  NFS_HASH("PS3_RANALOG_DOWN")
#define PS3_RANALOG_LEFT_HASH  NFS_HASH("PS3_RANALOG_LEFT")
#define PS3_RANALOG_RIGHT_HASH NFS_HASH("PS3_RANALOG_RIGHT")
#define PS3_RANALOG_UP_HASH    NFS_HASH("PS3_RANALOG_UP")
#define PS3_SELECT_HASH        NFS_HASH("PS3_SELECT")
#define PS3_SQUARE_HASH        NFS_HASH("PS3_SQUARE")
#define PS3_START_HASH         NFS_HASH("PS3_START")
#define PS3_TRIANGLE_HASH      NFS_HASH("PS3_TRIANGLE")

#define SWITCH_A_HASH          NFS_HASH("SWITCH_A")
#define SWITCH_B_HASH          NFS_HASH("SWITCH_B")
#define SWITCH_CAPTURE_HASH    NFS_HASH("SWITCH_CAPTURE")
#define SWITCH_DPAD_HASH       NFS_HASH("SWITCH_DPAD")
#define SWITCH_DPAD_DOWN_HASH  NFS_HASH("SWITCH_DPAD_DOWN")
#define SWITCH_DPAD_LEFT_HASH  NFS_HASH("SWITCH_DPAD_LEFT")
#define SWITCH_DPAD_RIGHT_HASH NFS_HASH("SWITCH_DPAD_RIGHT")
#define SWITCH_DPAD_UP_HASH    NFS_HASH("SWITCH_DPAD_UP")
#define SWITCH_DPAD_X_HASH     NFS_HASH("SWITCH_DPAD_X")
#define SWITCH_DPAD_Y_HASH     NFS_HASH("SWITCH_DPAD_Y")
// #define SWITCH_HOME_HASH			NFS_HASH("SWITCH_HOME")
#define SWITCH_L_HASH             NFS_HASH("SWITCH_L")
#define SWITCH_LANALOG_HASH       NFS_HASH("SWITCH_LANALOG")
#define SWITCH_LANALOG_DOWN_HASH  NFS_HASH("SWITCH_LANALOG_DOWN")
#define SWITCH_LANALOG_LEFT_HASH  NFS_HASH("SWITCH_LANALOG_LEFT")
#define SWITCH_LANALOG_RIGHT_HASH NFS_HASH("SWITCH_LANALOG_RIGHT")
#define SWITCH_LANALOG_UP_HASH    NFS_HASH("SWITCH_LANALOG_UP")
#define SWITCH_LANALOG_X_HASH     NFS_HASH("SWITCH_LANALOG_X")
#define SWITCH_LANALOG_Y_HASH     NFS_HASH("SWITCH_LANALOG_Y")
#define SWITCH_LS_HASH            NFS_HASH("SWITCH_LS")
#define SWITCH_MINUS_HASH         NFS_HASH("SWITCH_MINUS")
#define SWITCH_PLUS_HASH          NFS_HASH("SWITCH_PLUS")
#define SWITCH_R_HASH             NFS_HASH("SWITCH_R")
#define SWITCH_RANALOG_HASH       NFS_HASH("SWITCH_RANALOG")
#define SWITCH_RANALOG_DOWN_HASH  NFS_HASH("SWITCH_RANALOG_DOWN")
#define SWITCH_RANALOG_LEFT_HASH  NFS_HASH("SWITCH_RANALOG_LEFT")
#define SWITCH_RANALOG_RIGHT_HASH NFS_HASH("SWITCH_RANALOG_RIGHT")
#define SWITCH_RANALOG_UP_HASH    NFS_HASH("SWITCH_RANALOG_UP")
#define SWITCH_RANALOG_X_HASH     NFS_HASH("SWITCH_RANALOG_X")
#define SWITCH_RANALOG_Y_HASH     NFS_HASH("SWITCH_RANALOG_Y")
#define SWITCH_RS_HASH            NFS_HASH("SWITCH_RS")
#define SWITCH_X_HASH             NFS_HASH("SWITCH_X")
#define SWITCH_Y_HASH             NFS_HASH("SWITCH_Y")
#define SWITCH_ZL_HASH            NFS_HASH("SWITCH_ZL")
#define SWITCH_ZR_HASH            NFS_HASH("SWITCH_ZR")

#define XB360MW_A_HASH          NFS_HASH("XB360MW_A")
#define XB360MW_B_HASH          NFS_HASH("XB360MW_B")
#define XB360MW_BACK_HASH       NFS_HASH("XB360MW_BACK")
#define XB360MW_DPAD_HASH       NFS_HASH("XB360MW_DPAD")
#define XB360MW_DPAD_DOWN_HASH  NFS_HASH("XB360MW_DPAD_DOWN")
#define XB360MW_DPAD_LEFT_HASH  NFS_HASH("XB360MW_DPAD_LEFT")
#define XB360MW_DPAD_RIGHT_HASH NFS_HASH("XB360MW_DPAD_RIGHT")
#define XB360MW_DPAD_UP_HASH    NFS_HASH("XB360MW_DPAD_UP")
#define XB360MW_DPAD_X_HASH     NFS_HASH("XB360MW_DPAD_X")
#define XB360MW_DPAD_Y_HASH     NFS_HASH("XB360MW_DPAD_Y")
// #define XB360MW_GUIDE_HASH			NFS_HASH("XB360MW_GUIDE")
#define XB360MW_LANALOG_HASH       NFS_HASH("XB360MW_LANALOG")
#define XB360MW_LANALOG_DOWN_HASH  NFS_HASH("XB360MW_LANALOG_DOWN")
#define XB360MW_LANALOG_LEFT_HASH  NFS_HASH("XB360MW_LANALOG_LEFT")
#define XB360MW_LANALOG_RIGHT_HASH NFS_HASH("XB360MW_LANALOG_RIGHT")
#define XB360MW_LANALOG_UP_HASH    NFS_HASH("XB360MW_LANALOG_UP")
#define XB360MW_LB_HASH            NFS_HASH("XB360MW_LB")
#define XB360MW_LS_HASH            NFS_HASH("XB360MW_LS")
#define XB360MW_LT_HASH            NFS_HASH("XB360MW_LT")
#define XB360MW_RANALOG_HASH       NFS_HASH("XB360MW_RANALOG")
#define XB360MW_RANALOG_DOWN_HASH  NFS_HASH("XB360MW_RANALOG_DOWN")
#define XB360MW_RANALOG_LEFT_HASH  NFS_HASH("XB360MW_RANALOG_LEFT")
#define XB360MW_RANALOG_RIGHT_HASH NFS_HASH("XB360MW_RANALOG_RIGHT")
#define XB360MW_RANALOG_UP_HASH    NFS_HASH("XB360MW_RANALOG_UP")
#define XB360MW_RB_HASH            NFS_HASH("XB360MW_RB")
#define XB360MW_RS_HASH            NFS_HASH("XB360MW_RS")
#define XB360MW_RT_HASH            NFS_HASH("XB360MW_RT")
#define XB360MW_START_HASH         NFS_HASH("XB360MW_START")
#define XB360MW_X_HASH             NFS_HASH("XB360MW_X")
#define XB360MW_Y_HASH             NFS_HASH("XB360MW_Y")

int GetAppropriateButtonTex(WORD buttonmask) {
  switch (ControllerIconMode) {
    case CONTROLLERICON_PS3:
      switch (buttonmask) {
        case XINPUT_GAMEPAD_DPAD_UP:
          return PS3_DPAD_UP_HASH;
        case XINPUT_GAMEPAD_DPAD_DOWN:
          return PS3_DPAD_DOWN_HASH;
        case XINPUT_GAMEPAD_DPAD_LEFT:
          return PS3_DPAD_LEFT_HASH;
        case XINPUT_GAMEPAD_DPAD_RIGHT:
          return PS3_DPAD_RIGHT_HASH;
        case XINPUT_GAMEPAD_START:
          return PS3_START_HASH;
        case XINPUT_GAMEPAD_BACK:
          return PS3_SELECT_HASH;
        case XINPUT_GAMEPAD_LEFT_THUMB:
          return PS3_L3_HASH;
        case XINPUT_GAMEPAD_RIGHT_THUMB:
          return PS3_R3_HASH;
        case XINPUT_GAMEPAD_LEFT_SHOULDER:
          return PS3_L1_HASH;
        case XINPUT_GAMEPAD_RIGHT_SHOULDER:
          return PS3_R1_HASH;
        case XINPUT_GAMEPAD_A:
          return PS3_CROSS_HASH;
        case XINPUT_GAMEPAD_B:
          return PS3_CIRCLE_HASH;
        case XINPUT_GAMEPAD_X:
          return PS3_SQUARE_HASH;
        case XINPUT_GAMEPAD_Y:
          return PS3_TRIANGLE_HASH;
        case XINPUT_GAMEPAD_LT_CONFIGDEF:
          return PS3_L2_HASH;
        case XINPUT_GAMEPAD_RT_CONFIGDEF:
          return PS3_R2_HASH;
        case XINPUT_GAMEPAD_LS_X_CONFIGDEF:
          return PS3_LANALOG_HASH;
        case XINPUT_GAMEPAD_LS_Y_CONFIGDEF:
          return PS3_LANALOG_HASH;
        case XINPUT_GAMEPAD_RS_X_CONFIGDEF:
          return PS3_RANALOG_HASH;
        case XINPUT_GAMEPAD_RS_Y_CONFIGDEF:
          return PS3_RANALOG_HASH;
        case XINPUT_GAMEPAD_LS_UP_CONFIGDEF:
          return PS3_LANALOG_UP_HASH;
        case XINPUT_GAMEPAD_LS_DOWN_CONFIGDEF:
          return PS3_LANALOG_DOWN_HASH;
        case XINPUT_GAMEPAD_LS_LEFT_CONFIGDEF:
          return PS3_LANALOG_LEFT_HASH;
        case XINPUT_GAMEPAD_LS_RIGHT_CONFIGDEF:
          return PS3_LANALOG_RIGHT_HASH;
        case XINPUT_GAMEPAD_RS_UP_CONFIGDEF:
          return PS3_RANALOG_UP_HASH;
        case XINPUT_GAMEPAD_RS_DOWN_CONFIGDEF:
          return PS3_RANALOG_DOWN_HASH;
        case XINPUT_GAMEPAD_RS_LEFT_CONFIGDEF:
          return PS3_RANALOG_LEFT_HASH;
        case XINPUT_GAMEPAD_RS_RIGHT_CONFIGDEF:
          return PS3_RANALOG_RIGHT_HASH;
        case XINPUT_GAMEPAD_DPAD_CONFIGDEF:
          return PS3_DPAD_HASH;
        case XINPUT_GAMEPAD_DPAD_UPDOWN_CONFIGDEF:
          return PS3_DPAD_Y_HASH;
        case XINPUT_GAMEPAD_DPAD_LEFTRIGHT_CONFIGDEF:
          return PS3_DPAD_X_HASH;
        case XINPUT_GAMEPAD_LS_CONFIGDEF:
          return PS3_LANALOG_HASH;
        case XINPUT_GAMEPAD_RS_CONFIGDEF:
          return PS3_RANALOG_HASH;

        default:
          break;
      }
    case CONTROLLERICON_XBOX360:
      switch (buttonmask) {
        case XINPUT_GAMEPAD_DPAD_UP:
          return XB360_DPAD_UP_HASH;
        case XINPUT_GAMEPAD_DPAD_DOWN:
          return XB360_DPAD_DOWN_HASH;
        case XINPUT_GAMEPAD_DPAD_LEFT:
          return XB360_DPAD_LEFT_HASH;
        case XINPUT_GAMEPAD_DPAD_RIGHT:
          return XB360_DPAD_RIGHT_HASH;
        case XINPUT_GAMEPAD_START:
          return XB360_START_HASH;
        case XINPUT_GAMEPAD_BACK:
          return XB360_BACK_HASH;
        case XINPUT_GAMEPAD_LEFT_THUMB:
          return XB360_LS_HASH;
        case XINPUT_GAMEPAD_RIGHT_THUMB:
          return XB360_RS_HASH;
        case XINPUT_GAMEPAD_LEFT_SHOULDER:
          return XB360_LB_HASH;
        case XINPUT_GAMEPAD_RIGHT_SHOULDER:
          return XB360_RB_HASH;
        case XINPUT_GAMEPAD_A:
          return XB360_A_HASH;
        case XINPUT_GAMEPAD_B:
          return XB360_B_HASH;
        case XINPUT_GAMEPAD_X:
          return XB360_X_HASH;
        case XINPUT_GAMEPAD_Y:
          return XB360_Y_HASH;
        case XINPUT_GAMEPAD_LT_CONFIGDEF:
          return XB360_LT_HASH;
        case XINPUT_GAMEPAD_RT_CONFIGDEF:
          return XB360_RT_HASH;
        case XINPUT_GAMEPAD_LS_X_CONFIGDEF:
          return XB360_LANALOG_HASH;
        case XINPUT_GAMEPAD_LS_Y_CONFIGDEF:
          return XB360_LANALOG_HASH;
        case XINPUT_GAMEPAD_RS_X_CONFIGDEF:
          return XB360_RANALOG_HASH;
        case XINPUT_GAMEPAD_RS_Y_CONFIGDEF:
          return XB360_RANALOG_HASH;
        case XINPUT_GAMEPAD_LS_UP_CONFIGDEF:
          return XB360_LANALOG_UP_HASH;
        case XINPUT_GAMEPAD_LS_DOWN_CONFIGDEF:
          return XB360_LANALOG_DOWN_HASH;
        case XINPUT_GAMEPAD_LS_LEFT_CONFIGDEF:
          return XB360_LANALOG_LEFT_HASH;
        case XINPUT_GAMEPAD_LS_RIGHT_CONFIGDEF:
          return XB360_LANALOG_RIGHT_HASH;
        case XINPUT_GAMEPAD_RS_UP_CONFIGDEF:
          return XB360_RANALOG_UP_HASH;
        case XINPUT_GAMEPAD_RS_DOWN_CONFIGDEF:
          return XB360_RANALOG_DOWN_HASH;
        case XINPUT_GAMEPAD_RS_LEFT_CONFIGDEF:
          return XB360_RANALOG_LEFT_HASH;
        case XINPUT_GAMEPAD_RS_RIGHT_CONFIGDEF:
          return XB360_RANALOG_RIGHT_HASH;
        case XINPUT_GAMEPAD_DPAD_CONFIGDEF:
          return XB360_DPAD_HASH;
        case XINPUT_GAMEPAD_DPAD_UPDOWN_CONFIGDEF:
          return XB360_DPAD_Y_HASH;
        case XINPUT_GAMEPAD_DPAD_LEFTRIGHT_CONFIGDEF:
          return XB360_DPAD_X_HASH;
        case XINPUT_GAMEPAD_LS_CONFIGDEF:
          return XB360_LANALOG_HASH;
        case XINPUT_GAMEPAD_RS_CONFIGDEF:
          return XB360_RANALOG_HASH;

        default:
          break;
      }
    case CONTROLLERICON_PS4:
      switch (buttonmask) {
        case XINPUT_GAMEPAD_DPAD_UP:
          return PS4_DPAD_UP_HASH;
        case XINPUT_GAMEPAD_DPAD_DOWN:
          return PS4_DPAD_DOWN_HASH;
        case XINPUT_GAMEPAD_DPAD_LEFT:
          return PS4_DPAD_LEFT_HASH;
        case XINPUT_GAMEPAD_DPAD_RIGHT:
          return PS4_DPAD_RIGHT_HASH;
        case XINPUT_GAMEPAD_START:
          return PS4_START_HASH;
        case XINPUT_GAMEPAD_BACK:
          return PS4_SHARE_HASH;
        case XINPUT_GAMEPAD_LEFT_THUMB:
          return PS4_L3_HASH;
        case XINPUT_GAMEPAD_RIGHT_THUMB:
          return PS4_R3_HASH;
        case XINPUT_GAMEPAD_LEFT_SHOULDER:
          return PS4_L1_HASH;
        case XINPUT_GAMEPAD_RIGHT_SHOULDER:
          return PS4_R1_HASH;
        case XINPUT_GAMEPAD_A:
          return PS4_CROSS_HASH;
        case XINPUT_GAMEPAD_B:
          return PS4_CIRCLE_HASH;
        case XINPUT_GAMEPAD_X:
          return PS4_SQUARE_HASH;
        case XINPUT_GAMEPAD_Y:
          return PS4_TRIANGLE_HASH;
        case XINPUT_GAMEPAD_LT_CONFIGDEF:
          return PS4_L2_HASH;
        case XINPUT_GAMEPAD_RT_CONFIGDEF:
          return PS4_R2_HASH;
        case XINPUT_GAMEPAD_LS_X_CONFIGDEF:
          return PS4_LANALOG_X_HASH;
        case XINPUT_GAMEPAD_LS_Y_CONFIGDEF:
          return PS4_LANALOG_Y_HASH;
        case XINPUT_GAMEPAD_RS_X_CONFIGDEF:
          return PS4_RANALOG_X_HASH;
        case XINPUT_GAMEPAD_RS_Y_CONFIGDEF:
          return PS4_RANALOG_Y_HASH;
        case XINPUT_GAMEPAD_LS_UP_CONFIGDEF:
          return PS4_LANALOG_UP_HASH;
        case XINPUT_GAMEPAD_LS_DOWN_CONFIGDEF:
          return PS4_LANALOG_DOWN_HASH;
        case XINPUT_GAMEPAD_LS_LEFT_CONFIGDEF:
          return PS4_LANALOG_LEFT_HASH;
        case XINPUT_GAMEPAD_LS_RIGHT_CONFIGDEF:
          return PS4_LANALOG_RIGHT_HASH;
        case XINPUT_GAMEPAD_RS_UP_CONFIGDEF:
          return PS4_RANALOG_UP_HASH;
        case XINPUT_GAMEPAD_RS_DOWN_CONFIGDEF:
          return PS4_RANALOG_DOWN_HASH;
        case XINPUT_GAMEPAD_RS_LEFT_CONFIGDEF:
          return PS4_RANALOG_LEFT_HASH;
        case XINPUT_GAMEPAD_RS_RIGHT_CONFIGDEF:
          return PS4_RANALOG_RIGHT_HASH;
        case XINPUT_GAMEPAD_DPAD_CONFIGDEF:
          return PS4_DPAD_HASH;
        case XINPUT_GAMEPAD_DPAD_UPDOWN_CONFIGDEF:
          return PS4_DPAD_Y_HASH;
        case XINPUT_GAMEPAD_DPAD_LEFTRIGHT_CONFIGDEF:
          return PS4_DPAD_X_HASH;
        case XINPUT_GAMEPAD_LS_CONFIGDEF:
          return PS4_LANALOG_HASH;
        case XINPUT_GAMEPAD_RS_CONFIGDEF:
          return PS4_RANALOG_HASH;

        default:
          break;
      }
    case CONTROLLERICON_SWITCH:
      switch (buttonmask) {
        case XINPUT_GAMEPAD_DPAD_UP:
          return SWITCH_DPAD_UP_HASH;
        case XINPUT_GAMEPAD_DPAD_DOWN:
          return SWITCH_DPAD_DOWN_HASH;
        case XINPUT_GAMEPAD_DPAD_LEFT:
          return SWITCH_DPAD_LEFT_HASH;
        case XINPUT_GAMEPAD_DPAD_RIGHT:
          return SWITCH_DPAD_RIGHT_HASH;
        case XINPUT_GAMEPAD_START:
          return SWITCH_PLUS_HASH;
        case XINPUT_GAMEPAD_BACK:
          return SWITCH_MINUS_HASH;
        case XINPUT_GAMEPAD_LEFT_THUMB:
          return SWITCH_LS_HASH;
        case XINPUT_GAMEPAD_RIGHT_THUMB:
          return SWITCH_RS_HASH;
        case XINPUT_GAMEPAD_LEFT_SHOULDER:
          return SWITCH_L_HASH;
        case XINPUT_GAMEPAD_RIGHT_SHOULDER:
          return SWITCH_R_HASH;
        case XINPUT_GAMEPAD_A:
          return SWITCH_B_HASH;
        case XINPUT_GAMEPAD_B:
          return SWITCH_A_HASH;
        case XINPUT_GAMEPAD_X:
          return SWITCH_Y_HASH;
        case XINPUT_GAMEPAD_Y:
          return SWITCH_X_HASH;
        case XINPUT_GAMEPAD_LT_CONFIGDEF:
          return SWITCH_ZL_HASH;
        case XINPUT_GAMEPAD_RT_CONFIGDEF:
          return SWITCH_ZR_HASH;
        case XINPUT_GAMEPAD_LS_X_CONFIGDEF:
          return SWITCH_LANALOG_HASH;
        case XINPUT_GAMEPAD_LS_Y_CONFIGDEF:
          return SWITCH_LANALOG_HASH;
        case XINPUT_GAMEPAD_RS_X_CONFIGDEF:
          return SWITCH_RANALOG_HASH;
        case XINPUT_GAMEPAD_RS_Y_CONFIGDEF:
          return SWITCH_RANALOG_HASH;
        case XINPUT_GAMEPAD_LS_UP_CONFIGDEF:
          return SWITCH_LANALOG_UP_HASH;
        case XINPUT_GAMEPAD_LS_DOWN_CONFIGDEF:
          return SWITCH_LANALOG_DOWN_HASH;
        case XINPUT_GAMEPAD_LS_LEFT_CONFIGDEF:
          return SWITCH_LANALOG_LEFT_HASH;
        case XINPUT_GAMEPAD_LS_RIGHT_CONFIGDEF:
          return SWITCH_LANALOG_RIGHT_HASH;
        case XINPUT_GAMEPAD_RS_UP_CONFIGDEF:
          return SWITCH_RANALOG_UP_HASH;
        case XINPUT_GAMEPAD_RS_DOWN_CONFIGDEF:
          return SWITCH_RANALOG_DOWN_HASH;
        case XINPUT_GAMEPAD_RS_LEFT_CONFIGDEF:
          return SWITCH_RANALOG_LEFT_HASH;
        case XINPUT_GAMEPAD_RS_RIGHT_CONFIGDEF:
          return SWITCH_RANALOG_RIGHT_HASH;
        case XINPUT_GAMEPAD_DPAD_CONFIGDEF:
          return SWITCH_DPAD_HASH;
        case XINPUT_GAMEPAD_DPAD_UPDOWN_CONFIGDEF:
          return SWITCH_DPAD_Y_HASH;
        case XINPUT_GAMEPAD_DPAD_LEFTRIGHT_CONFIGDEF:
          return SWITCH_DPAD_X_HASH;
        case XINPUT_GAMEPAD_LS_CONFIGDEF:
          return SWITCH_LANALOG_HASH;
        case XINPUT_GAMEPAD_RS_CONFIGDEF:
          return SWITCH_RANALOG_HASH;

        default:
          break;
      }
    case CONTROLLERICON_XB360MW:
      switch (buttonmask) {
        case XINPUT_GAMEPAD_DPAD_UP:
          return XB360MW_DPAD_UP_HASH;
        case XINPUT_GAMEPAD_DPAD_DOWN:
          return XB360MW_DPAD_DOWN_HASH;
        case XINPUT_GAMEPAD_DPAD_LEFT:
          return XB360MW_DPAD_LEFT_HASH;
        case XINPUT_GAMEPAD_DPAD_RIGHT:
          return XB360MW_DPAD_RIGHT_HASH;
        case XINPUT_GAMEPAD_START:
          return XB360MW_START_HASH;
        case XINPUT_GAMEPAD_BACK:
          return XB360MW_BACK_HASH;
        case XINPUT_GAMEPAD_LEFT_THUMB:
          return XB360MW_LS_HASH;
        case XINPUT_GAMEPAD_RIGHT_THUMB:
          return XB360MW_RS_HASH;
        case XINPUT_GAMEPAD_LEFT_SHOULDER:
          return XB360MW_LB_HASH;
        case XINPUT_GAMEPAD_RIGHT_SHOULDER:
          return XB360MW_RB_HASH;
        case XINPUT_GAMEPAD_A:
          return XB360MW_A_HASH;
        case XINPUT_GAMEPAD_B:
          return XB360MW_B_HASH;
        case XINPUT_GAMEPAD_X:
          return XB360MW_X_HASH;
        case XINPUT_GAMEPAD_Y:
          return XB360MW_Y_HASH;
        case XINPUT_GAMEPAD_LT_CONFIGDEF:
          return XB360MW_LT_HASH;
        case XINPUT_GAMEPAD_RT_CONFIGDEF:
          return XB360MW_RT_HASH;
        case XINPUT_GAMEPAD_LS_X_CONFIGDEF:
          return XB360MW_LANALOG_HASH;
        case XINPUT_GAMEPAD_LS_Y_CONFIGDEF:
          return XB360MW_LANALOG_HASH;
        case XINPUT_GAMEPAD_RS_X_CONFIGDEF:
          return XB360MW_RANALOG_HASH;
        case XINPUT_GAMEPAD_RS_Y_CONFIGDEF:
          return XB360MW_RANALOG_HASH;
        case XINPUT_GAMEPAD_LS_UP_CONFIGDEF:
          return XB360MW_LANALOG_UP_HASH;
        case XINPUT_GAMEPAD_LS_DOWN_CONFIGDEF:
          return XB360MW_LANALOG_DOWN_HASH;
        case XINPUT_GAMEPAD_LS_LEFT_CONFIGDEF:
          return XB360MW_LANALOG_LEFT_HASH;
        case XINPUT_GAMEPAD_LS_RIGHT_CONFIGDEF:
          return XB360MW_LANALOG_RIGHT_HASH;
        case XINPUT_GAMEPAD_RS_UP_CONFIGDEF:
          return XB360MW_RANALOG_UP_HASH;
        case XINPUT_GAMEPAD_RS_DOWN_CONFIGDEF:
          return XB360MW_RANALOG_DOWN_HASH;
        case XINPUT_GAMEPAD_RS_LEFT_CONFIGDEF:
          return XB360MW_RANALOG_LEFT_HASH;
        case XINPUT_GAMEPAD_RS_RIGHT_CONFIGDEF:
          return XB360MW_RANALOG_RIGHT_HASH;
        case XINPUT_GAMEPAD_DPAD_CONFIGDEF:
          return XB360MW_DPAD_HASH;
        case XINPUT_GAMEPAD_DPAD_UPDOWN_CONFIGDEF:
          return XB360MW_DPAD_Y_HASH;
        case XINPUT_GAMEPAD_DPAD_LEFTRIGHT_CONFIGDEF:
          return XB360MW_DPAD_X_HASH;
        case XINPUT_GAMEPAD_LS_CONFIGDEF:
          return XB360MW_LANALOG_HASH;
        case XINPUT_GAMEPAD_RS_CONFIGDEF:
          return XB360MW_RANALOG_HASH;

        default:
          break;
      }
    case CONTROLLERICON_XBOXONE:
    default:
      switch (buttonmask) {
        case XINPUT_GAMEPAD_DPAD_UP:
          return XBONE_DPAD_UP_HASH;
        case XINPUT_GAMEPAD_DPAD_DOWN:
          return XBONE_DPAD_DOWN_HASH;
        case XINPUT_GAMEPAD_DPAD_LEFT:
          return XBONE_DPAD_LEFT_HASH;
        case XINPUT_GAMEPAD_DPAD_RIGHT:
          return XBONE_DPAD_RIGHT_HASH;
        case XINPUT_GAMEPAD_START:
          return XBONE_MENU_HASH;
        case XINPUT_GAMEPAD_BACK:
          return XBONE_VIEW_HASH;
        case XINPUT_GAMEPAD_LEFT_THUMB:
          return XBONE_LS_HASH;
        case XINPUT_GAMEPAD_RIGHT_THUMB:
          return XBONE_RS_HASH;
        case XINPUT_GAMEPAD_LEFT_SHOULDER:
          return XBONE_LB_HASH;
        case XINPUT_GAMEPAD_RIGHT_SHOULDER:
          return XBONE_RB_HASH;
        case XINPUT_GAMEPAD_A:
          return XBONE_A_HASH;
        case XINPUT_GAMEPAD_B:
          return XBONE_B_HASH;
        case XINPUT_GAMEPAD_X:
          return XBONE_X_HASH;
        case XINPUT_GAMEPAD_Y:
          return XBONE_Y_HASH;
        case XINPUT_GAMEPAD_LT_CONFIGDEF:
          return XBONE_LT_HASH;
        case XINPUT_GAMEPAD_RT_CONFIGDEF:
          return XBONE_RT_HASH;
        case XINPUT_GAMEPAD_LS_X_CONFIGDEF:
          return XBONE_LANALOG_X_HASH;
        case XINPUT_GAMEPAD_LS_Y_CONFIGDEF:
          return XBONE_LANALOG_Y_HASH;
        case XINPUT_GAMEPAD_RS_X_CONFIGDEF:
          return XBONE_RANALOG_X_HASH;
        case XINPUT_GAMEPAD_RS_Y_CONFIGDEF:
          return XBONE_RANALOG_Y_HASH;
        case XINPUT_GAMEPAD_LS_UP_CONFIGDEF:
          return XBONE_LANALOG_UP_HASH;
        case XINPUT_GAMEPAD_LS_DOWN_CONFIGDEF:
          return XBONE_LANALOG_DOWN_HASH;
        case XINPUT_GAMEPAD_LS_LEFT_CONFIGDEF:
          return XBONE_LANALOG_LEFT_HASH;
        case XINPUT_GAMEPAD_LS_RIGHT_CONFIGDEF:
          return XBONE_LANALOG_RIGHT_HASH;
        case XINPUT_GAMEPAD_RS_UP_CONFIGDEF:
          return XBONE_RANALOG_UP_HASH;
        case XINPUT_GAMEPAD_RS_DOWN_CONFIGDEF:
          return XBONE_RANALOG_DOWN_HASH;
        case XINPUT_GAMEPAD_RS_LEFT_CONFIGDEF:
          return XBONE_RANALOG_LEFT_HASH;
        case XINPUT_GAMEPAD_RS_RIGHT_CONFIGDEF:
          return XBONE_RANALOG_RIGHT_HASH;
        case XINPUT_GAMEPAD_DPAD_CONFIGDEF:
          return XBONE_DPAD_HASH;
        case XINPUT_GAMEPAD_DPAD_UPDOWN_CONFIGDEF:
          return XBONE_DPAD_Y_HASH;
        case XINPUT_GAMEPAD_DPAD_LEFTRIGHT_CONFIGDEF:
          return XBONE_DPAD_X_HASH;
        case XINPUT_GAMEPAD_LS_CONFIGDEF:
          return XBONE_LANALOG_HASH;
        case XINPUT_GAMEPAD_RS_CONFIGDEF:
          return XBONE_RANALOG_HASH;

        default:
          break;
      }
      break;
  }
  return 0;
}
